labels:
  matrixone.cloud/rule-type: metric
  matrixone.cloud/unit-name: default
groups:
- name: mo.cn.metric.rules
  rules:
  # cn 协程暴增报警
  # cn 协程数目在长达半个小时一直保持在超高水准的时候报警
  - alert: CNGoroutineGrow
    expr: go_goroutines{matrixorigin_io_component="CNSet"} > 10000
    for: 30m
    labels:
      severity: "warning"
      # serviceScope: mo-cluster
      serviceScope: test
      alertOwner: nnsmgsone
      alertTeam: "CN2 Team"
      namespace: "{{ $labels.namespace }}"
      pod: "{{ $labels.namespace }}"
    annotations:
      summary: "CN pod {{ $labels.pod }} in {{ $labels.namespace }} : CN goroutine growing greatly for 30 min"
      description: "CN pod {{ $labels.pod }} in {{ $labels.namespace }} : CN goroutine growing greatly for 30 min"
  # cn 磁盘利用率
  # cn 长时间磁盘利用率 90% 的时候就需要告警并且扩容
  - alert: CNVolumeOutOfDiskSpace
    expr: kubelet_volume_stats_available_bytes{persistentvolumeclaim=~"mo-data.*cn.*"} / kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~"mo-data.*cn.*"} * 100 < 10
    for: 5m
    labels:
      severity: "warning"
      # serviceScope: mo-cluster
      serviceScope: test
      alertOwner: nnsmgsone
      alertTeam: "CN2 Team"
      pvc: "{{ $labels.persistentvolumeclaim }}"
      pvcNamespace: "{{ $labels.namespace }}"
    annotations:
      summary: CN Persistent Volume out of disk space is almost full
      description: "CN Persistent Volume Claim {{ $labels.persistentvolumeclaim }}'s volume in {{ $labels.namespace }} is almost full with {{ $value }} (< 10% left)"
  # cn 内存占用异常
  # 内存占用达到oom kill的 90%
  - alert: CNMemoryUsageHigh
    expr: sum by (pod) (container_memory_working_set_bytes{pod=~".*-cn-.*",container!="", image!=""}) / sum by (pod) (kube_pod_container_resource_limits{pod=~".*-cn-.*", job="kubernetes-service-endpoints"}) * 100  >= 90
    for: 1m
    labels:
      severity: "ctitical"
      # serviceScope: mo-cluster
      serviceScope: test
      alertOwner: nnsmgsone
      alertTeam: "CN2 Team"
      namespace: "{{ $labels.namespace }}"
      pod: "{{ $labels.namespace }}"
    annotations:
      summary: "CN pod {{ $labels.pod }} in {{ $labels.namespace }} : CN memory usage approach to 90% of limit"
      description: "CN pod {{ $labels.pod }} in {{ $labels.namespace }} : CN memory usage approach to 90% of limit"
  # CN Commit耗时异常
  # mo_txn_commit_duration_seconds{type="cn"}，该指标出现超过5秒
  - alert: CNCommitTxnDurationLong
    expr: rate(mo_txn_commit_duration_seconds_sum{type="cn", matrixorigin_io_component="CNSet"}[1m]) / rate(mo_txn_commit_duration_seconds_count{type="cn", matrixorigin_io_component="CNSet"}[1m]) > 5
    # histogram_quantile(0.99, rate(mo_txn_commit_duration_seconds_bucket{type="cn"}[1m])) > 5
    for: 0m
    labels:
      severity: "warning"
      # serviceScope: mo-cluster
      serviceScope: test
      alertOwner: xupeng
      alertTeam: "DN Team"
      pod: "{{$labels.pod}}"
      namespace: "{{ $labels.namespace }}"
    annotations:
      summary: "CN pod {{ $labels.pod }} in {{ $labels.namespace }} : CN commit txn take more than 5s"
      description: "CN pod {{ $labels.pod }} in {{ $labels.namespace }} : CN commit txn take more than 5s"
  # Checkpoint 长时间未做告警
  # mo_task_long_duration_seconds_count{type="ckp_entry_pending"} 该 count 超过半小时没有增加
  - alert: NoCheckpoint
    expr: sum by(namespace, pod) (increase(mo_task_long_duration_seconds_count{matrixorigin_io_component="DNSet", type="ckp_entry_pending"}[1m])) == 0
    for: 30m
    labels:
      severity: "warning"
      serviceScope: mo-cluster
      alertOwner: HanFeng
      alertTeam: "DN Team"
      namespace: "{{ $labels.namespace }}"
      pod: "{{ $labels.namespace }}"
    annotations:
      summary: "CN pod {{ $labels.pod }} in {{ $labels.namespace }} : Checkpoint is not working more than 30 mins"
      description: "CN pod {{ $labels.pod }} in {{ $labels.namespace }} : Checkpoint is not working more than 30 mins"
