labels:
  matrixone.cloud/rule-type: metric
  matrixone.cloud/unit-name: default
groups:
- name: mo.dn.metric.rules
  rules:
  # DN 处理commit的缓冲队列堆积
  # mo_txn_queue_size{type="commit"}，该指标队列 5分钟之内一直 >0，并且没有下降
  - alert: DNConsumeTxnQueueGrow
    expr: (min_over_time(mo_txn_queue_size{type="commit", matrixorigin_io_component="DNSet"}[1m]) > 0) and (deriv(mo_txn_queue_size{type="commit", matrixorigin_io_component="DNSet"}[1m]) >= 0)
    for: 5m
    labels:
      severity: "warning"
      # serviceScope: mo-cluster
      serviceScope: test
      alertOwner: xupeng
      alertTeam: "DN Team"
      namespace: "{{ $labels.namespace }}"
      pod: "{{ $labels.namespace }}"
    annotations:
      summary: "DN pod {{ $labels.pod }} in {{ $labels.namespace }} : DN consume txn queue stuck, mo_txn_queue_size{type=commit} is growing"
      description: "DN pod {{ $labels.pod }} in {{ $labels.namespace }} : DN consume txn queue stuck, mo_txn_queue_size{type=commit} is growing"
  # TN merge 未正常进行
  # mo_task_scheduled_by_total{type="merge"} 这个指标如果半小时没有增加，需要做告警
  - alert: TN_Merge_Stuck
    expr: sum by(namespace, pod)  (increase(mo_task_scheduled_by_total{type="merge", matrixorigin_io_component="DNSet", job="kubernetes-service-endpoints"}[1m])) <= 0
    for: 30m
    labels:
      severity: "warning"
      serviceScope: mo-cluster
      alertOwner: HanFeng
      alertTeam: "DN Team"
      namespace: "{{ $labels.namespace }}"
      pod: "{{ $labels.pod }}"
    annotations:
      summary: "DN pod {{ $labels.pod }} in {{ $labels.namespace }} : TN Merge stuck, mo_task_scheduled_by_total{type=merge} is not growing"
      description: "DN pod {{ $labels.pod }} in {{ $labels.namespace }} : TN Merge stuck, mo_task_scheduled_by_total{type=merge} is not growing"
