labels:
  matrixone.cloud/rule-type: metric
  matrixone.cloud/unit-name: default
groups:
- name: mo.logservice.metric.rules
  rules:
  # Log Service磁盘占用告警
  # 当 Log Service 使用的 PV 即将用满时 (剩余容量 <= 10%) 进行告警
  - alert: LogServiceVolumeOutOfDiskSpace
    expr: kubelet_volume_stats_available_bytes{persistentvolumeclaim=~"mo-data.*log.*"} / kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~"mo-data.*log.*"} * 100 < 10
    for: 0m
    labels:
      severity: "warning"
      # serviceScope: mo-cluster
      serviceScope: test
      alertOwner: bol
      alertTeam: "DN Team"
      pvc: "{{ $labels.persistentvolumeclaim }}"
      pvcNamespace: "{{ $labels.namespace }}"
    annotations:
      summary: Log Service Persistent Volume out of disk space is almost full
      description: "Log Service Persistent Volume Claim {{ $labels.persistentvolumeclaim }}'s volume in {{ $labels.namespace }} is almost full with {{ $value }} (< 10% left)"
  # CN接收 Logtail 异常
  # mo_logtail_received_total{type="total"}，该指标 1 分钟停止增长
  - alert: CNReceiveLogtailError
    expr: rate(mo_logtail_received_total{type="total", matrixorigin_io_component="CNSet"}[1m]) == 0
    for: 0m
    labels:
      severity: "critical"
      # serviceScope: mo-cluster
      serviceScope: test
      alertOwner: bol
      alertTeam: "DN Team"
      namespace: "{{ $labels.namespace }}"
      pod: "{{ $labels.namespace }}"
    annotations:
      summary: "CN pod {{ $labels.pod }} in {{ $labels.namespace }} : CN no receive from logtail for 1 min"
      description: "CN pod {{ $labels.pod }} in {{ $labels.namespace }} : CN no receive from logtail for 1 min"
  # CN消费 Logtail 堆积
  # mo_logtail_queue_size{type="apply"}，该指标 1 分钟一直 >0
  # FIXME 有可能一直大于 0
  - alert: CNReceiveLogtailStuck
    expr: min_over_time(mo_logtail_queue_size{type="apply", matrixorigin_io_component="CNSet"}[1m]) > 0
    for: 0m
    labels:
      severity: "warning"
      # serviceScope: mo-cluster
      serviceScope: test
      alertOwner: bol
      alertTeam: "DN Team"
      namespace: "{{ $labels.namespace }}"
      pod: "{{ $labels.namespace }}"
    annotations:
      summary: "CN pod {{ $labels.pod }} in {{ $labels.namespace }} : CN logtail queue size larger than 0 for 1min"
      description: "CN pod {{ $labels.pod }} in {{ $labels.namespace }} : CN logtail queue size larger than 0 for 1min"
  # DN写 Logtail 时间过久
  # mo_logtail_append_duration_seconds，出现超过5s
  - alert: DNAppendLogtailStuck
    expr: rate(mo_logtail_append_duration_seconds_sum{matrixorigin_io_component="DNSet"}[1m]) / rate(mo_logtail_append_duration_seconds_count{matrixorigin_io_component="DNSet"}[1m])> 5
    # histogram_quantile(0.99, rate(mo_logtail_append_duration_seconds_bucket{matrixorigin_io_component="DNSet"}[1m])) > 5
    for: 0m
    labels:
      severity: "warning"
      # serviceScope: mo-cluster
      serviceScope: test
      alertOwner: bol
      alertTeam: "DN Team"
      namespace: "{{ $labels.namespace }}"
      pod: "{{ $labels.namespace }}"
    annotations:
      summary: "DN pod {{ $labels.pod }} in {{ $labels.namespace }} : Logtail stuck append to DN, avg time consume takes 5s"
      description: "DN pod {{ $labels.pod }} in {{ $labels.namespace }} : Logtail stuck append to DN, avg time consume takes 5s"
