labels:
  matrixone.cloud/rule-type: metric
  matrixone.cloud/unit-name: default
groups:
- name: mo.txn.metric.rules
  rules:
  # CN 没有事务commit
  # mo_txn_commit_total{type="cn"}，该指标 1 分钟没有增长
  - alert: TxnNoCommit
    expr: increase(mo_txn_commit_total{type="cn", matrixorigin_io_component="CNSet"}[1m]) == 0
    for: 0m
    labels:
      severity: "warning"
      # serviceScope: mo-cluster
      serviceScope: test
      alertOwner: zx
      alertTeam: "CN2 Team"
      namespace: "{{ $labels.namespace }}"
      pod: "{{ $labels.namespace }}"
    annotations:
      summary: "CN pod {{ $labels.pod }} in {{ $labels.namespace }} : txn commit not growing for 1 min"
      description: "CN pod {{ $labels.pod }} in {{ $labels.namespace }} : txn commit not growing for 1 min"
  # CN 回滚事务持续增长
  # mo_txn_rollback_total ，该指标 1 分钟之内一直增长
  - alert: TxnRollbackGrow
    expr: rate(mo_txn_rollback_total{matrixorigin_io_component="CNSet"}[1m]) > 0
    for: 1m
    labels:
      severity: "critical"
      # serviceScope: mo-cluster
      serviceScope: test
      alertOwner: zx
      alertTeam: "CN2 Team"
      pod: "{{$labels.pod}}"
      namespace: "{{ $labels.namespace }}"
    annotations:
      summary: "CN pod {{ $labels.pod }} in {{ $labels.namespace }} : rollback txn grow for 1 min"
      description: "CN pod {{ $labels.pod }} in {{ $labels.namespace }} : rollback txn grow for 1 min"
  # CN 等待活跃事务队列增长
  # mo_txn_queue_size {type="wait-active"}，该指标 5 分钟内一直增长
  - alert: TxnWaitActiveQueueGrow
    expr: deriv(mo_txn_queue_size{type="wait-active", matrixorigin_io_component="CNSet"}[1m]) > 0
    for: 5m
    labels:
      severity: "critical"
      # serviceScope: mo-cluster
      serviceScope: test
      alertOwner: zx
      alertTeam: "CN2 Team"
      pod: "{{$labels.pod}}"
      namespace: "{{ $labels.namespace }}"
    annotations:
      summary: "CN pod {{ $labels.pod }} in {{ $labels.namespace }} : wait active txn queue size keep growing for 5 min"
      description: "CN pod {{ $labels.pod }} in {{ $labels.namespace }} : wait active txn queue size keep growing for 5 min"
  # 事务卡在等待活跃事务
  # mo_txn_create_duration_seconds{type="wait-active"}，该指标出现超过10s
  - alert: TxnStuckInWaitActive
    expr: rate(mo_txn_create_duration_seconds_sum{type="wait-active", matrixorigin_io_component="CNSet"}[1m]) / rate(mo_txn_create_duration_seconds_count{type="wait-active", matrixorigin_io_component="CNSet"}[1m]) > 10
    # histogram_quantile(0.99, rate(mo_txn_create_duration_seconds_bucket{type="wait-active"}[1m])) > 10
    for: 0m
    labels:
      severity: "critical"
      # serviceScope: mo-cluster
      serviceScope: test
      alertOwner: zx
      alertTeam: "CN2 Team"
      pod: "{{$labels.pod}}"
      namespace: "{{ $labels.namespace }}"
    annotations:
      summary: "CN pod {{ $labels.pod }} in {{ $labels.namespace }} : Txn stuck in wait active for 10s"
      description: "CN pod {{ $labels.pod }} in {{ $labels.namespace }} : Txn stuck in wait active for 10s"
