labels:
  matrixone.cloud/rule-type: metric
  matrixone.cloud/unit-name: default
groups:
  - name: mocloud.unit-agent.metric.rules
    rules:
    - alert: CreateNodePoolFailed
      expr: increase(unit_agent_aliyun_sdk_error{api="create_nodepool"}[5m]) > 0
      for: 1m
      labels:
        severity: "warning"
        serviceScope: mo-cloud
        alertOwner: qiuweimin
        alertTeam: "Orch Team"
        api: "{{ $labels.api }}"
      annotations:
        summary: "aliyun sdk {{ $labels.api }} report error, view pod {{ $labels.pod }} log for detail"
        description: "aliyun sdk {{ $labels.api }} report error, view pod {{ $labels.pod }} log for detail"
    - alert: ConvertECS2PostPaidFailed
      expr: increase(unit_agent_aliyun_sdk_error{api="convert_postpaid"}[5m]) > 0
      for: 1m
      labels:
        severity: "warning"
        serviceScope: mo-cloud
        alertOwner: qiuweimin
        alertTeam: "Orch Team"
        api: "{{ $labels.api }}"
      annotations:
        summary: "aliyun sdk {{ $labels.api }} report error, view pod {{ $labels.pod }} log for detail"
        description: "aliyun sdk {{ $labels.api }} report error, view pod {{ $labels.pod }} log for detail"
    - alert: RenewECSFailed
      expr: increase(unit_agent_aliyun_sdk_error{api="renew_ecs"}[5m]) > 0
      for: 1m
      labels:
        severity: "warning"
        serviceScope: mo-cloud
        alertOwner: qiuweimin
        alertTeam: "Orch Team"
        api: "{{ $labels.api }}"
      annotations:
        summary: "aliyun sdk {{ $labels.api }} report error, view pod {{ $labels.pod }} log for detail"
        description: "aliyun sdk {{ $labels.api }} report error, view pod {{ $labels.pod }} log for detail"
    - alert: ReleaseNodeFromPool
      expr: increase(unit_agent_aliyun_sdk_error{api="release_node_from_pool"}[5m]) > 0
      for: 1m
      labels:
        severity: "warning"
        serviceScope: mo-cloud
        alertOwner: qiuweimin
        alertTeam: "Orch Team"
        api: "{{ $labels.api }}"
      annotations:
        summary: "aliyun sdk {{ $labels.api }} report error, view pod {{ $labels.pod }} log for detail"
        description: "aliyun sdk {{ $labels.api }} report error, view pod {{ $labels.pod }} log for detail"