labels:
  matrixone.cloud/rule-type: metric
  matrixone.cloud/unit-name: default
  matrixone.cloud/control-plane: "true"
groups:
  - name: mocloud.cos.metric.rules
    rules:
    - alert: OrchPodNotReady
      expr: min_over_time(sum by (namespace, pod, phase) (kube_pod_status_phase{phase=~"Pending|Unknown|Failed"})[5m:1m]) > 0
      for: 10m
      labels:
        severity: "warning"
        serviceScope: mo-cloud
        alertOwner: qiuweimin
        alertTeam: "Orch Team"
        namespace: "{{ $labels.namespace }}"
        pod: "{{ $labels.pod }}"
        podPhase: "{{ $labels.phase }}"
      annotations:
        summary: "pod {{ $labels.pod }} in {{ $labels.namespace }} {{ $labels.phase }} for 10 minutes"
        description: "pod {{ $labels.pod }} in {{ $labels.namespace }} {{ $labels.phase }} for 10 minutes"
    - alert: OrchPodFrequentlyRestart
      expr: sum_over_time(increase(kube_pod_container_status_restarts_total{}[1m])[5m:1m]) > 3
      for: 3m # note: 1) 3min is not a strict value; 2) pod restart in exponential backoff, like 0s, 10s, 20s, 40s, ...
      labels:
        severity: "warning"
        serviceScope: mo-cloud
        alertOwner: qiuweimin
        alertTeam: "Orch Team"
        namespace: "{{ $labels.namespace }}"
        pod: "{{ $labels.pod }}"
      annotations:
        summary: "pod {{ $labels.pod }} in {{ $labels.namespace }} restart more than 3 times in 5 minutes"
        description: "pod {{ $labels.pod }} in {{ $labels.namespace }} restart more than 3 times in 5 minutes"
    - alert: OrchPVCNotReady
      expr: min_over_time(sum by (namespace, persistentvolumeclaim, phase) (kube_persistentvolumeclaim_status_phase{phase=~"Pending|Lost"})[5m:1m]) > 0
      for: 10m
      labels:
        severity: "warning"
        serviceScope: mo-cloud
        alertOwner: qiuweimin
        alertTeam: "Orch Team"
        namespace: "{{ $labels.namespace }}"
        pvc: "{{ $labels.persistentvolumeclaim }}"
        pvcPhase: "{{ $labels.phase }}"
      annotations:
        summary: "pvc {{ $labels.persistentvolumeclaim }} in {{ $labels.namespace }} {{ $labels.phase }} for 10 minutes"
        description: "pvc {{ $labels.persistentvolumeclaim }} in {{ $labels.namespace }} {{ $labels.phase }} for 10 minutes"