labels:
  matrixone.cloud/rule-type: metric
  matrixone.cloud/unit-name: default
  matrixone.cloud/control-plane: "true"
groups:
  - name: ob.infra.metric.rules
    rules:
    - alert: PrometheusSeriesLongTimeIncrease
      expr: deriv(prometheus_tsdb_head_series{job=~".+",instance=~".+"}[5m]) > 5
      for: 30m
      labels:
        severity: "warning"
        serviceScope: mo-cloud
        alertOwner: jacksonxie
        alertTeam: "Orch Team"
      annotations:
        summary: prometheus series increase last 30min, rate > 5 ops
        description: "{{ $labels.instance }} collect Series increase lasts 30 min"
    - alert: PrometheusMemoryUsageHigh
      expr: sum by(pod) (container_memory_working_set_bytes{pod=~".*prometheus.*", container="prometheus", image!=""}) / sum by(pod) (kube_pod_container_resource_limits{pod=~".*prometheus.*", container="prometheus", resource="memory"}) * 100.0 > 76.6
      for: 5m
      labels:
        severity: "warning"
        serviceScope: mo-cluster
        alertOwner: jacksonxie
        alertTeam: "Orch Team"
        pod: "{{ $labels.pod }}"
      annotations:
        summary: "Prometheus pod {{ $labels.pod }} memory usage over 76.6%"
        description: "Prometheus pod {{ $labels.pod }} memory usage over 76.6%: {{ $value }}"
    - alert: MOOBDiskUsage
      expr: max by (namespace, persistentvolumeclaim) ( (kubelet_volume_stats_capacity_bytes{job="kubelet", metrics_path="/metrics", namespace="mo-ob"} - kubelet_volume_stats_available_bytes{job="kubelet", metrics_path="/metrics", namespace="mo-ob"}) / kubelet_volume_stats_capacity_bytes{job="kubelet", metrics_path="/metrics", namespace="mo-ob"} * 100) > 90.0
      for: 30m
      labels:
        severity: "warning"
        serviceScope: mo-cloud
        alertOwner: jacksonxie
        alertTeam: "Orch Team"
      annotations:
        summary: moob pv usage > 90.0 % (last 30min)
        description: "{{ $labels.persistentvolumeclaim }} usage > 90.0 % lasts 30min: {{ $value }}"
    - alert: PromTsdbCompactionFailed
      expr: increase(prometheus_tsdb_compactions_failed_total{namespace="mo-ob"}[1m]) > 0
      for: 0m
      labels:
        severity: "warning"
        serviceScope: mo-cloud
        alertOwner: jacksonxie
        alertTeam: "Orch Team"
      annotations:
        summary: "promethes tsdb compactions failed, more in moc#2705"
        description: "promethes tsdb compactions failed"
  - name: ob.infra.charts
    rules:
    - alert: PromtailDroppEntries
      # filter by job to avoid duplicate metrics
      expr: rate(promtail_dropped_entries_total[1m]) > 0
      for: 0m
      labels:
        alertname: PromtailDroppEntries
        severity: "warning"
        serviceScope: mo-ob
        alertOwner: bruce
        alertTeam: "Orch Team"
      annotations:
        summary: "{{$labels.pod}}/{{$labels.instance}}: promtail drop logs because of {{$labels.reason}}"
        description: "{{$labels.pod}}/{{$labels.instance}}: promtail drop logs because of {{$labels.reason}}"
