{
 "title": "FileService Overview",
 "panels": [
  {
   "title": "S3 Read requests",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mo_fs_read_total{type=\"s3\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))",
     "legendFormat": "s3"
    },
    {
     "expr": "sum(rate(mo_fs_read_total{type=\"hit-mem\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))",
     "legendFormat": "hit-mem"
    },
    {
     "expr": "sum(rate(mo_fs_read_total{type=\"hit-disk\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))",
     "legendFormat": "hit-disk"
    },
    {
     "expr": "sum(rate(mo_fs_read_total{type=\"hit-remote\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))",
     "legendFormat": "hit-remote"
    }
   ]
  },
  {
   "title": "S3 Write requests",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mo_fs_write_total{type=\"s3\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))",
     "legendFormat": "s3"
    },
    {
     "expr": "sum(rate(mo_fs_write_total{type=\"local\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))",
     "legendFormat": "local"
    }
   ]
  }
 ]
}
{
 "title": "FileService io merger duration",
 "panels": [
  {
   "title": "P90.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "seconds" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_fs_io_merger_duration_seconds_bucket{type=\"wait\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "wait"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_fs_io_merger_duration_seconds_bucket{type=\"initiate\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "initiate"
    }
   ]
  },
  {
   "title": "P99.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "seconds" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_fs_io_merger_duration_seconds_bucket{type=\"wait\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "wait"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_fs_io_merger_duration_seconds_bucket{type=\"initiate\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "initiate"
    }
   ]
  },
  {
   "title": "P100.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "seconds" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1.000000, sum(rate(mo_fs_io_merger_duration_seconds_bucket{type=\"wait\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "wait"
    },
    {
     "expr": "histogram_quantile(1.000000, sum(rate(mo_fs_io_merger_duration_seconds_bucket{type=\"initiate\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "initiate"
    }
   ]
  }
 ]
}
{
 "title": "FileService read write duration",
 "panels": [
  {
   "title": "P90.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "seconds" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_fs_read_write_duration_bucket{type=\"read-vector-cache\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "read-vector-cache"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_fs_read_write_duration_bucket{type=\"update-vector-cache\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "update-vector-cache"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_fs_read_write_duration_bucket{type=\"read-memory-cache\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "read-memory-cache"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_fs_read_write_duration_bucket{type=\"update-memory-cache\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "update-memory-cache"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_fs_read_write_duration_bucket{type=\"read-disk-cache\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "read-disk-cache"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_fs_read_write_duration_bucket{type=\"update-disk-cache\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "update-disk-cache"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_fs_read_write_duration_bucket{type=\"read-remote-cache\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "read-remote-cache"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_fs_read_write_duration_bucket{type=\"get-reader\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "get-reader"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_fs_read_write_duration_bucket{type=\"get-content\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "get-content"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_fs_read_write_duration_bucket{type=\"get-entry-data \",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "get-entry-data "
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_fs_read_write_duration_bucket{type=\"write-to-writer\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "write-to-writer"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_fs_read_write_duration_bucket{type=\"set-cached-data\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "set-cached-data"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_fs_read_write_duration_bucket{type=\"disk-cache-set-file\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "disk-cache-set-file"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_fs_read_write_duration_bucket{type=\"list\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "list"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_fs_read_write_duration_bucket{type=\"stat\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "stat"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_fs_read_write_duration_bucket{type=\"write\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "write"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_fs_read_write_duration_bucket{type=\"io-read-all\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "io-read-all"
    }
   ]
  },
  {
   "title": "P99.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "seconds" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_fs_read_write_duration_bucket{type=\"read-vector-cache\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "read-vector-cache"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_fs_read_write_duration_bucket{type=\"update-vector-cache\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "update-vector-cache"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_fs_read_write_duration_bucket{type=\"read-memory-cache\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "read-memory-cache"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_fs_read_write_duration_bucket{type=\"update-memory-cache\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "update-memory-cache"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_fs_read_write_duration_bucket{type=\"read-disk-cache\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "read-disk-cache"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_fs_read_write_duration_bucket{type=\"update-disk-cache\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "update-disk-cache"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_fs_read_write_duration_bucket{type=\"read-remote-cache\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "read-remote-cache"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_fs_read_write_duration_bucket{type=\"get-reader\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "get-reader"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_fs_read_write_duration_bucket{type=\"get-content\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "get-content"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_fs_read_write_duration_bucket{type=\"get-entry-data \",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "get-entry-data "
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_fs_read_write_duration_bucket{type=\"write-to-writer\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "write-to-writer"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_fs_read_write_duration_bucket{type=\"set-cached-data\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "set-cached-data"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_fs_read_write_duration_bucket{type=\"disk-cache-set-file\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "disk-cache-set-file"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_fs_read_write_duration_bucket{type=\"list\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "list"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_fs_read_write_duration_bucket{type=\"stat\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "stat"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_fs_read_write_duration_bucket{type=\"write\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "write"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_fs_read_write_duration_bucket{type=\"io-read-all\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "io-read-all"
    }
   ]
  },
  {
   "title": "P100.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "seconds" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1.000000, sum(rate(mo_fs_read_write_duration_bucket{type=\"read-vector-cache\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "read-vector-cache"
    },
    {
     "expr": "histogram_quantile(1.000000, sum(rate(mo_fs_read_write_duration_bucket{type=\"update-vector-cache\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "update-vector-cache"
    },
    {
     "expr": "histogram_quantile(1.000000, sum(rate(mo_fs_read_write_duration_bucket{type=\"read-memory-cache\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "read-memory-cache"
    },
    {
     "expr": "histogram_quantile(1.000000, sum(rate(mo_fs_read_write_duration_bucket{type=\"update-memory-cache\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "update-memory-cache"
    },
    {
     "expr": "histogram_quantile(1.000000, sum(rate(mo_fs_read_write_duration_bucket{type=\"read-disk-cache\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "read-disk-cache"
    },
    {
     "expr": "histogram_quantile(1.000000, sum(rate(mo_fs_read_write_duration_bucket{type=\"update-disk-cache\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "update-disk-cache"
    },
    {
     "expr": "histogram_quantile(1.000000, sum(rate(mo_fs_read_write_duration_bucket{type=\"read-remote-cache\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "read-remote-cache"
    },
    {
     "expr": "histogram_quantile(1.000000, sum(rate(mo_fs_read_write_duration_bucket{type=\"get-reader\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "get-reader"
    },
    {
     "expr": "histogram_quantile(1.000000, sum(rate(mo_fs_read_write_duration_bucket{type=\"get-content\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "get-content"
    },
    {
     "expr": "histogram_quantile(1.000000, sum(rate(mo_fs_read_write_duration_bucket{type=\"get-entry-data \",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "get-entry-data "
    },
    {
     "expr": "histogram_quantile(1.000000, sum(rate(mo_fs_read_write_duration_bucket{type=\"write-to-writer\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "write-to-writer"
    },
    {
     "expr": "histogram_quantile(1.000000, sum(rate(mo_fs_read_write_duration_bucket{type=\"set-cached-data\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "set-cached-data"
    },
    {
     "expr": "histogram_quantile(1.000000, sum(rate(mo_fs_read_write_duration_bucket{type=\"disk-cache-set-file\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "disk-cache-set-file"
    },
    {
     "expr": "histogram_quantile(1.000000, sum(rate(mo_fs_read_write_duration_bucket{type=\"list\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "list"
    },
    {
     "expr": "histogram_quantile(1.000000, sum(rate(mo_fs_read_write_duration_bucket{type=\"stat\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "stat"
    },
    {
     "expr": "histogram_quantile(1.000000, sum(rate(mo_fs_read_write_duration_bucket{type=\"write\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "write"
    },
    {
     "expr": "histogram_quantile(1.000000, sum(rate(mo_fs_read_write_duration_bucket{type=\"io-read-all\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "io-read-all"
    }
   ]
  }
 ]
}
{
 "title": "malloc stats",
 "panels": [
  {
   "title": "active objects",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mo_fs_malloc_live_objects{type=\"io_entry_data\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"})",
     "legendFormat": "io_entry_data"
    },
    {
     "expr": "sum(mo_fs_malloc_live_objects{type=\"bytes\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"})",
     "legendFormat": "bytes"
    },
    {
     "expr": "sum(mo_fs_malloc_live_objects{type=\"memory_cache\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"})",
     "legendFormat": "memory_cache"
    }
   ]
  }
 ]
}
{
 "title": "FileService read write bytes",
 "panels": [
  {
   "title": "P50.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_fs_s3_io_bytes_bucket{type=\"read\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "s3-read"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_fs_s3_io_bytes_bucket{type=\"write\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "s3-write"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_fs_local_io_bytes_bucket{type=\"read\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "local-read"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_fs_local_io_bytes_bucket{type=\"write\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "local-write"
    }
   ]
  },
  {
   "title": "P80.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_fs_s3_io_bytes_bucket{type=\"read\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "s3-read"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_fs_s3_io_bytes_bucket{type=\"write\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "s3-write"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_fs_local_io_bytes_bucket{type=\"read\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "local-read"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_fs_local_io_bytes_bucket{type=\"write\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "local-write"
    }
   ]
  },
  {
   "title": "P90.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_fs_s3_io_bytes_bucket{type=\"read\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "s3-read"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_fs_s3_io_bytes_bucket{type=\"write\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "s3-write"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_fs_local_io_bytes_bucket{type=\"read\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "local-read"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_fs_local_io_bytes_bucket{type=\"write\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "local-write"
    }
   ]
  },
  {
   "title": "P99.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_fs_s3_io_bytes_bucket{type=\"read\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "s3-read"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_fs_s3_io_bytes_bucket{type=\"write\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "s3-write"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_fs_local_io_bytes_bucket{type=\"read\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "local-read"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_fs_local_io_bytes_bucket{type=\"write\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "local-write"
    }
   ]
  }
 ]
}
{
 "title": "FileService S3 connection overview",
 "panels": [
  {
   "title": "Connect",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mo_fs_s3_conn_duration_seconds_count{type=\"connect\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))"
    }
   ]
  },
  {
   "title": "DNS Resolve",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mo_fs_s3_conn_duration_seconds_count{type=\"dns-resolve\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))"
    }
   ]
  }
 ]
}
{
 "title": "FileService s3 connection duration",
 "panels": [
  {
   "title": "P50.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_fs_s3_conn_duration_seconds_bucket{type=\"connect\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "connect"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_fs_s3_conn_duration_seconds_bucket{type=\"get-conn\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "get-conn"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_fs_s3_conn_duration_seconds_bucket{type=\"dns-resolve\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "dns-resolve"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_fs_s3_conn_duration_seconds_bucket{type=\"tls-handshake\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "tls-handshake"
    }
   ]
  },
  {
   "title": "P80.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_fs_s3_conn_duration_seconds_bucket{type=\"connect\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "connect"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_fs_s3_conn_duration_seconds_bucket{type=\"get-conn\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "get-conn"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_fs_s3_conn_duration_seconds_bucket{type=\"dns-resolve\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "dns-resolve"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_fs_s3_conn_duration_seconds_bucket{type=\"tls-handshake\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "tls-handshake"
    }
   ]
  },
  {
   "title": "P90.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_fs_s3_conn_duration_seconds_bucket{type=\"connect\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "connect"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_fs_s3_conn_duration_seconds_bucket{type=\"get-conn\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "get-conn"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_fs_s3_conn_duration_seconds_bucket{type=\"dns-resolve\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "dns-resolve"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_fs_s3_conn_duration_seconds_bucket{type=\"tls-handshake\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "tls-handshake"
    }
   ]
  },
  {
   "title": "P99.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_fs_s3_conn_duration_seconds_bucket{type=\"connect\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "connect"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_fs_s3_conn_duration_seconds_bucket{type=\"get-conn\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "get-conn"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_fs_s3_conn_duration_seconds_bucket{type=\"dns-resolve\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "dns-resolve"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_fs_s3_conn_duration_seconds_bucket{type=\"tls-handshake\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "tls-handshake"
    }
   ]
  }
 ]
}