{
 "title": "Accept Connection Duration",
 "panels": [
  {
   "title": "P50.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_frontend_accept_connection_duration_bucket{label=\"created\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "created"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_frontend_accept_connection_duration_bucket{label=\"establish\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "establish"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_frontend_accept_connection_duration_bucket{label=\"upgradeTLS\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "upgradeTLS"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_frontend_accept_connection_duration_bucket{label=\"authenticate\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "authenticate"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_frontend_accept_connection_duration_bucket{label=\"check-tenant\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "check-tenant"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_frontend_accept_connection_duration_bucket{label=\"check-user\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "check-user"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_frontend_accept_connection_duration_bucket{label=\"check-role\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "check-role"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_frontend_accept_connection_duration_bucket{label=\"check-dbname\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "check-dbname"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_frontend_accept_connection_duration_bucket{label=\"init-global-sys-var\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "init-global-sys-var"
    }
   ]
  },
  {
   "title": "P80.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_frontend_accept_connection_duration_bucket{label=\"created\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "created"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_frontend_accept_connection_duration_bucket{label=\"establish\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "establish"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_frontend_accept_connection_duration_bucket{label=\"upgradeTLS\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "upgradeTLS"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_frontend_accept_connection_duration_bucket{label=\"authenticate\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "authenticate"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_frontend_accept_connection_duration_bucket{label=\"check-tenant\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "check-tenant"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_frontend_accept_connection_duration_bucket{label=\"check-user\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "check-user"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_frontend_accept_connection_duration_bucket{label=\"check-role\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "check-role"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_frontend_accept_connection_duration_bucket{label=\"check-dbname\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "check-dbname"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_frontend_accept_connection_duration_bucket{label=\"init-global-sys-var\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "init-global-sys-var"
    }
   ]
  },
  {
   "title": "P90.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_frontend_accept_connection_duration_bucket{label=\"created\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "created"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_frontend_accept_connection_duration_bucket{label=\"establish\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "establish"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_frontend_accept_connection_duration_bucket{label=\"upgradeTLS\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "upgradeTLS"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_frontend_accept_connection_duration_bucket{label=\"authenticate\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "authenticate"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_frontend_accept_connection_duration_bucket{label=\"check-tenant\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "check-tenant"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_frontend_accept_connection_duration_bucket{label=\"check-user\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "check-user"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_frontend_accept_connection_duration_bucket{label=\"check-role\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "check-role"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_frontend_accept_connection_duration_bucket{label=\"check-dbname\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "check-dbname"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_frontend_accept_connection_duration_bucket{label=\"init-global-sys-var\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "init-global-sys-var"
    }
   ]
  },
  {
   "title": "P99.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_frontend_accept_connection_duration_bucket{label=\"created\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "created"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_frontend_accept_connection_duration_bucket{label=\"establish\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "establish"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_frontend_accept_connection_duration_bucket{label=\"upgradeTLS\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "upgradeTLS"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_frontend_accept_connection_duration_bucket{label=\"authenticate\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "authenticate"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_frontend_accept_connection_duration_bucket{label=\"check-tenant\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "check-tenant"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_frontend_accept_connection_duration_bucket{label=\"check-user\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "check-user"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_frontend_accept_connection_duration_bucket{label=\"check-role\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "check-role"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_frontend_accept_connection_duration_bucket{label=\"check-dbname\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "check-dbname"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_frontend_accept_connection_duration_bucket{label=\"init-global-sys-var\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "init-global-sys-var"
    }
   ]
  }
 ]
}
{
 "title": "Routine and request count",
 "panels": [
  {
   "title": "Routine Count",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mo_frontend_routine_count{label=\"created\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))",
     "legendFormat": "created"
    },
    {
     "expr": "sum(rate(mo_frontend_routine_count{label=\"close\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))",
     "legendFormat": "close"
    }
   ]
  },
  {
   "title": "Request Count",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mo_frontend_request_count{label=\"start-handle\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))",
     "legendFormat": "start-handle"
    },
    {
     "expr": "sum(rate(mo_frontend_request_count{label=\"end-handle\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))",
     "legendFormat": "end-handle"
    }
   ]
  }
 ]
}
{
 "title": "Resolve Duration",
 "panels": [
  {
   "title": "P50.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_frontend_resolve_duration_bucket{label=\"total-resolve\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "total-resolve"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_frontend_resolve_duration_bucket{label=\"ensure-database\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "ensure-database"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_frontend_resolve_duration_bucket{label=\"get-sub-meta\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "get-sub-meta"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_frontend_resolve_duration_bucket{label=\"check-sub-valid\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "check-sub-valid"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_frontend_resolve_duration_bucket{label=\"get-relation\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "get-relation"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_frontend_resolve_duration_bucket{label=\"open-db\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "open-db"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_frontend_resolve_duration_bucket{label=\"open-table\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "open-table"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_frontend_resolve_duration_bucket{label=\"get-tmp-table\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "get-tmp-table"
    }
   ]
  },
  {
   "title": "P80.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_frontend_resolve_duration_bucket{label=\"total-resolve\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "total-resolve"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_frontend_resolve_duration_bucket{label=\"ensure-database\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "ensure-database"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_frontend_resolve_duration_bucket{label=\"get-sub-meta\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "get-sub-meta"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_frontend_resolve_duration_bucket{label=\"check-sub-valid\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "check-sub-valid"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_frontend_resolve_duration_bucket{label=\"get-relation\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "get-relation"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_frontend_resolve_duration_bucket{label=\"open-db\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "open-db"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_frontend_resolve_duration_bucket{label=\"open-table\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "open-table"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_frontend_resolve_duration_bucket{label=\"get-tmp-table\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "get-tmp-table"
    }
   ]
  },
  {
   "title": "P90.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_frontend_resolve_duration_bucket{label=\"total-resolve\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "total-resolve"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_frontend_resolve_duration_bucket{label=\"ensure-database\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "ensure-database"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_frontend_resolve_duration_bucket{label=\"get-sub-meta\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "get-sub-meta"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_frontend_resolve_duration_bucket{label=\"check-sub-valid\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "check-sub-valid"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_frontend_resolve_duration_bucket{label=\"get-relation\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "get-relation"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_frontend_resolve_duration_bucket{label=\"open-db\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "open-db"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_frontend_resolve_duration_bucket{label=\"open-table\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "open-table"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_frontend_resolve_duration_bucket{label=\"get-tmp-table\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "get-tmp-table"
    }
   ]
  },
  {
   "title": "P99.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_frontend_resolve_duration_bucket{label=\"total-resolve\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "total-resolve"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_frontend_resolve_duration_bucket{label=\"ensure-database\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "ensure-database"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_frontend_resolve_duration_bucket{label=\"get-sub-meta\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "get-sub-meta"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_frontend_resolve_duration_bucket{label=\"check-sub-valid\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "check-sub-valid"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_frontend_resolve_duration_bucket{label=\"get-relation\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "get-relation"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_frontend_resolve_duration_bucket{label=\"open-db\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "open-db"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_frontend_resolve_duration_bucket{label=\"open-table\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "open-table"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_frontend_resolve_duration_bucket{label=\"get-tmp-table\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "get-tmp-table"
    }
   ]
  }
 ]
}
{
 "title": "Create account Duration",
 "panels": [
  {
   "title": "P50.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_frontend_create_account_duration_bucket{label=\"total-create\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "total-create"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_frontend_create_account_duration_bucket{label=\"step1\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "step1"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_frontend_create_account_duration_bucket{label=\"step2\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "step2"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_frontend_create_account_duration_bucket{label=\"create-tables-in-mo-catalog\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "create-tables-in-mo-catalog"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_frontend_create_account_duration_bucket{label=\"exec-ddl1\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "exec-ddl1"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_frontend_create_account_duration_bucket{label=\"init-data1\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "init-data1"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_frontend_create_account_duration_bucket{label=\"create-tables-in-system\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "create-tables-in-system"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_frontend_create_account_duration_bucket{label=\"create-tables-in-info-schema\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "create-tables-in-info-schema"
    }
   ]
  },
  {
   "title": "P80.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_frontend_create_account_duration_bucket{label=\"total-create\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "total-create"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_frontend_create_account_duration_bucket{label=\"step1\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "step1"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_frontend_create_account_duration_bucket{label=\"step2\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "step2"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_frontend_create_account_duration_bucket{label=\"create-tables-in-mo-catalog\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "create-tables-in-mo-catalog"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_frontend_create_account_duration_bucket{label=\"exec-ddl1\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "exec-ddl1"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_frontend_create_account_duration_bucket{label=\"init-data1\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "init-data1"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_frontend_create_account_duration_bucket{label=\"create-tables-in-system\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "create-tables-in-system"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_frontend_create_account_duration_bucket{label=\"create-tables-in-info-schema\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "create-tables-in-info-schema"
    }
   ]
  },
  {
   "title": "P90.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_frontend_create_account_duration_bucket{label=\"total-create\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "total-create"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_frontend_create_account_duration_bucket{label=\"step1\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "step1"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_frontend_create_account_duration_bucket{label=\"step2\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "step2"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_frontend_create_account_duration_bucket{label=\"create-tables-in-mo-catalog\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "create-tables-in-mo-catalog"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_frontend_create_account_duration_bucket{label=\"exec-ddl1\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "exec-ddl1"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_frontend_create_account_duration_bucket{label=\"init-data1\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "init-data1"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_frontend_create_account_duration_bucket{label=\"create-tables-in-system\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "create-tables-in-system"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_frontend_create_account_duration_bucket{label=\"create-tables-in-info-schema\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "create-tables-in-info-schema"
    }
   ]
  },
  {
   "title": "P99.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_frontend_create_account_duration_bucket{label=\"total-create\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "total-create"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_frontend_create_account_duration_bucket{label=\"step1\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "step1"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_frontend_create_account_duration_bucket{label=\"step2\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "step2"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_frontend_create_account_duration_bucket{label=\"create-tables-in-mo-catalog\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "create-tables-in-mo-catalog"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_frontend_create_account_duration_bucket{label=\"exec-ddl1\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "exec-ddl1"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_frontend_create_account_duration_bucket{label=\"init-data1\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "init-data1"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_frontend_create_account_duration_bucket{label=\"create-tables-in-system\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "create-tables-in-system"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_frontend_create_account_duration_bucket{label=\"create-tables-in-info-schema\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "create-tables-in-info-schema"
    }
   ]
  }
 ]
}
{
 "title": "Input SQL Length",
 "panels": [
  {
   "title": "P50.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_frontend_sql_length_bucket{label=\"total-sql-length\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "total-sql-length"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_frontend_sql_length_bucket{label=\"load-data-inline-sql-length\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "load-data-inline-sql-length"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_frontend_sql_length_bucket{label=\"other-sql-length\"\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "other-sql-length"
    }
   ]
  },
  {
   "title": "P80.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_frontend_sql_length_bucket{label=\"total-sql-length\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "total-sql-length"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_frontend_sql_length_bucket{label=\"load-data-inline-sql-length\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "load-data-inline-sql-length"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_frontend_sql_length_bucket{label=\"other-sql-length\"\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "other-sql-length"
    }
   ]
  },
  {
   "title": "P90.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_frontend_sql_length_bucket{label=\"total-sql-length\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "total-sql-length"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_frontend_sql_length_bucket{label=\"load-data-inline-sql-length\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "load-data-inline-sql-length"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_frontend_sql_length_bucket{label=\"other-sql-length\"\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "other-sql-length"
    }
   ]
  },
  {
   "title": "P99.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_frontend_sql_length_bucket{label=\"total-sql-length\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "total-sql-length"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_frontend_sql_length_bucket{label=\"load-data-inline-sql-length\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "load-data-inline-sql-length"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_frontend_sql_length_bucket{label=\"other-sql-length\"\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "other-sql-length"
    }
   ]
  }
 ]
}