{
 "title": "Memory",
 "panels": [
  {
   "title": "/memory/classes/heap/free:bytes",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_memory_classes_heap_free_bytes{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "/memory/classes/heap/objects:bytes",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_memory_classes_heap_objects_bytes{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "/memory/classes/heap/released:bytes",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_memory_classes_heap_released_bytes{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "/memory/classes/heap/stacks:bytes",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_memory_classes_heap_stacks_bytes{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "/memory/classes/heap/unused:bytes",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_memory_classes_heap_unused_bytes{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "/memory/classes/metadata/mcache/free:bytes",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_memory_classes_metadata_mcache_free_bytes{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "/memory/classes/metadata/mcache/inuse:bytes",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_memory_classes_metadata_mcache_inuse_bytes{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "/memory/classes/metadata/mspan/free:bytes",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_memory_classes_metadata_mspan_free_bytes{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "/memory/classes/metadata/mspan/inuse:bytes",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_memory_classes_metadata_mspan_inuse_bytes{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "/memory/classes/metadata/other:bytes",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_memory_classes_metadata_other_bytes{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "/memory/classes/os-stacks:bytes",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_memory_classes_os_stacks_bytes{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "/memory/classes/other:bytes",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_memory_classes_other_bytes{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "/memory/classes/profiling/buckets:bytes",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_memory_classes_profiling_buckets_bytes{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "/memory/classes/total:bytes",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_memory_classes_total_bytes{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}
{
 "title": "GC",
 "panels": [
  {
   "title": "/gc/cycles/automatic:gc-cycles",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_gc_cycles_automatic_gc_cycles_total{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "rate: /gc/cycles/automatic:gc-cycles",
   "type": "graph",
   "yaxes": [
    { "format": "gc-cycles" }
   ],
   "targets": [
    {
     "expr": "sum(rate(go_gc_cycles_automatic_gc_cycles_total{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "/gc/cycles/forced:gc-cycles",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_gc_cycles_forced_gc_cycles_total{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "rate: /gc/cycles/forced:gc-cycles",
   "type": "graph",
   "yaxes": [
    { "format": "gc-cycles" }
   ],
   "targets": [
    {
     "expr": "sum(rate(go_gc_cycles_forced_gc_cycles_total{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "/gc/cycles/total:gc-cycles",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_gc_cycles_total_gc_cycles_total{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "rate: /gc/cycles/total:gc-cycles",
   "type": "graph",
   "yaxes": [
    { "format": "gc-cycles" }
   ],
   "targets": [
    {
     "expr": "sum(rate(go_gc_cycles_total_gc_cycles_total{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "/gc/gogc:percent",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_gc_gogc_percent{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "/gc/gomemlimit:bytes",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_gc_gomemlimit_bytes{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "/gc/heap/allocs-by-size:bytes",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.800000, sum(rate(go_gc_heap_allocs_by_size_bytes_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P80.00%"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(go_gc_heap_allocs_by_size_bytes_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P90.00%"
    },
    {
     "expr": "histogram_quantile(0.950000, sum(rate(go_gc_heap_allocs_by_size_bytes_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P95.00%"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(go_gc_heap_allocs_by_size_bytes_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P99.00%"
    }
   ]
  },
  {
   "title": "/gc/heap/allocs:bytes",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_gc_heap_allocs_bytes_total{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "rate: /gc/heap/allocs:bytes",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(go_gc_heap_allocs_bytes_total{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "/gc/heap/allocs:objects",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_gc_heap_allocs_objects_total{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "rate: /gc/heap/allocs:objects",
   "type": "graph",
   "yaxes": [
    { "format": "objects" }
   ],
   "targets": [
    {
     "expr": "sum(rate(go_gc_heap_allocs_objects_total{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "/gc/heap/frees-by-size:bytes",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.800000, sum(rate(go_gc_heap_frees_by_size_bytes_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P80.00%"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(go_gc_heap_frees_by_size_bytes_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P90.00%"
    },
    {
     "expr": "histogram_quantile(0.950000, sum(rate(go_gc_heap_frees_by_size_bytes_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P95.00%"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(go_gc_heap_frees_by_size_bytes_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P99.00%"
    }
   ]
  },
  {
   "title": "/gc/heap/frees:bytes",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_gc_heap_frees_bytes_total{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "rate: /gc/heap/frees:bytes",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(go_gc_heap_frees_bytes_total{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "/gc/heap/frees:objects",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_gc_heap_frees_objects_total{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "rate: /gc/heap/frees:objects",
   "type": "graph",
   "yaxes": [
    { "format": "objects" }
   ],
   "targets": [
    {
     "expr": "sum(rate(go_gc_heap_frees_objects_total{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "/gc/heap/goal:bytes",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_gc_heap_goal_bytes{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "/gc/heap/live:bytes",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_gc_heap_live_bytes{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "/gc/heap/objects:objects",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_gc_heap_objects_objects{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "/gc/heap/tiny/allocs:objects",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_gc_heap_tiny_allocs_objects_total{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "rate: /gc/heap/tiny/allocs:objects",
   "type": "graph",
   "yaxes": [
    { "format": "objects" }
   ],
   "targets": [
    {
     "expr": "sum(rate(go_gc_heap_tiny_allocs_objects_total{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "/gc/limiter/last-enabled:gc-cycle",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_gc_limiter_last_enabled_gc_cycle{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "/gc/pauses:seconds",
   "type": "graph",
   "yaxes": [
    { "format": "seconds" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.800000, sum(rate(go_gc_pauses_seconds_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P80.00%"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(go_gc_pauses_seconds_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P90.00%"
    },
    {
     "expr": "histogram_quantile(0.950000, sum(rate(go_gc_pauses_seconds_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P95.00%"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(go_gc_pauses_seconds_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P99.00%"
    }
   ]
  },
  {
   "title": "/gc/scan/globals:bytes",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_gc_scan_globals_bytes{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "/gc/scan/heap:bytes",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_gc_scan_heap_bytes{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "/gc/scan/stack:bytes",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_gc_scan_stack_bytes{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "/gc/scan/total:bytes",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_gc_scan_total_bytes{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "/gc/stack/starting-size:bytes",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_gc_stack_starting_size_bytes{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}
{
 "title": "CPU",
 "panels": [
  {
   "title": "/cpu/classes/gc/mark/assist:cpu-seconds",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_cpu_classes_gc_mark_assist_cpu_seconds_total{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "rate: /cpu/classes/gc/mark/assist:cpu-seconds",
   "type": "graph",
   "yaxes": [
    { "format": "cpu-seconds" }
   ],
   "targets": [
    {
     "expr": "sum(rate(go_cpu_classes_gc_mark_assist_cpu_seconds_total{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "/cpu/classes/gc/mark/dedicated:cpu-seconds",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_cpu_classes_gc_mark_dedicated_cpu_seconds_total{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "rate: /cpu/classes/gc/mark/dedicated:cpu-seconds",
   "type": "graph",
   "yaxes": [
    { "format": "cpu-seconds" }
   ],
   "targets": [
    {
     "expr": "sum(rate(go_cpu_classes_gc_mark_dedicated_cpu_seconds_total{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "/cpu/classes/gc/mark/idle:cpu-seconds",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_cpu_classes_gc_mark_idle_cpu_seconds_total{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "rate: /cpu/classes/gc/mark/idle:cpu-seconds",
   "type": "graph",
   "yaxes": [
    { "format": "cpu-seconds" }
   ],
   "targets": [
    {
     "expr": "sum(rate(go_cpu_classes_gc_mark_idle_cpu_seconds_total{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "/cpu/classes/gc/pause:cpu-seconds",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_cpu_classes_gc_pause_cpu_seconds_total{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "rate: /cpu/classes/gc/pause:cpu-seconds",
   "type": "graph",
   "yaxes": [
    { "format": "cpu-seconds" }
   ],
   "targets": [
    {
     "expr": "sum(rate(go_cpu_classes_gc_pause_cpu_seconds_total{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "/cpu/classes/gc/total:cpu-seconds",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_cpu_classes_gc_total_cpu_seconds_total{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "rate: /cpu/classes/gc/total:cpu-seconds",
   "type": "graph",
   "yaxes": [
    { "format": "cpu-seconds" }
   ],
   "targets": [
    {
     "expr": "sum(rate(go_cpu_classes_gc_total_cpu_seconds_total{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "/cpu/classes/idle:cpu-seconds",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_cpu_classes_idle_cpu_seconds_total{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "rate: /cpu/classes/idle:cpu-seconds",
   "type": "graph",
   "yaxes": [
    { "format": "cpu-seconds" }
   ],
   "targets": [
    {
     "expr": "sum(rate(go_cpu_classes_idle_cpu_seconds_total{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "/cpu/classes/scavenge/assist:cpu-seconds",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_cpu_classes_scavenge_assist_cpu_seconds_total{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "rate: /cpu/classes/scavenge/assist:cpu-seconds",
   "type": "graph",
   "yaxes": [
    { "format": "cpu-seconds" }
   ],
   "targets": [
    {
     "expr": "sum(rate(go_cpu_classes_scavenge_assist_cpu_seconds_total{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "/cpu/classes/scavenge/background:cpu-seconds",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_cpu_classes_scavenge_background_cpu_seconds_total{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "rate: /cpu/classes/scavenge/background:cpu-seconds",
   "type": "graph",
   "yaxes": [
    { "format": "cpu-seconds" }
   ],
   "targets": [
    {
     "expr": "sum(rate(go_cpu_classes_scavenge_background_cpu_seconds_total{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "/cpu/classes/scavenge/total:cpu-seconds",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_cpu_classes_scavenge_total_cpu_seconds_total{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "rate: /cpu/classes/scavenge/total:cpu-seconds",
   "type": "graph",
   "yaxes": [
    { "format": "cpu-seconds" }
   ],
   "targets": [
    {
     "expr": "sum(rate(go_cpu_classes_scavenge_total_cpu_seconds_total{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "/cpu/classes/total:cpu-seconds",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_cpu_classes_total_cpu_seconds_total{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "rate: /cpu/classes/total:cpu-seconds",
   "type": "graph",
   "yaxes": [
    { "format": "cpu-seconds" }
   ],
   "targets": [
    {
     "expr": "sum(rate(go_cpu_classes_total_cpu_seconds_total{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "/cpu/classes/user:cpu-seconds",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_cpu_classes_user_cpu_seconds_total{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "rate: /cpu/classes/user:cpu-seconds",
   "type": "graph",
   "yaxes": [
    { "format": "cpu-seconds" }
   ],
   "targets": [
    {
     "expr": "sum(rate(go_cpu_classes_user_cpu_seconds_total{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}
{
 "title": "Schedule",
 "panels": [
  {
   "title": "/sched/gomaxprocs:threads",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_sched_gomaxprocs_threads{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "/sched/goroutines:goroutines",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_sched_goroutines_goroutines{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "/sched/latencies:seconds",
   "type": "graph",
   "yaxes": [
    { "format": "seconds" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.800000, sum(rate(go_sched_latencies_seconds_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P80.00%"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(go_sched_latencies_seconds_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P90.00%"
    },
    {
     "expr": "histogram_quantile(0.950000, sum(rate(go_sched_latencies_seconds_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P95.00%"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(go_sched_latencies_seconds_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P99.00%"
    }
   ]
  },
  {
   "title": "/sched/pauses/stopping/gc:seconds",
   "type": "graph",
   "yaxes": [
    { "format": "seconds" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.800000, sum(rate(go_sched_pauses_stopping_gc_seconds_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P80.00%"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(go_sched_pauses_stopping_gc_seconds_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P90.00%"
    },
    {
     "expr": "histogram_quantile(0.950000, sum(rate(go_sched_pauses_stopping_gc_seconds_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P95.00%"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(go_sched_pauses_stopping_gc_seconds_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P99.00%"
    }
   ]
  },
  {
   "title": "/sched/pauses/stopping/other:seconds",
   "type": "graph",
   "yaxes": [
    { "format": "seconds" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.800000, sum(rate(go_sched_pauses_stopping_other_seconds_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P80.00%"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(go_sched_pauses_stopping_other_seconds_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P90.00%"
    },
    {
     "expr": "histogram_quantile(0.950000, sum(rate(go_sched_pauses_stopping_other_seconds_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P95.00%"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(go_sched_pauses_stopping_other_seconds_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P99.00%"
    }
   ]
  },
  {
   "title": "/sched/pauses/total/gc:seconds",
   "type": "graph",
   "yaxes": [
    { "format": "seconds" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.800000, sum(rate(go_sched_pauses_total_gc_seconds_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P80.00%"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(go_sched_pauses_total_gc_seconds_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P90.00%"
    },
    {
     "expr": "histogram_quantile(0.950000, sum(rate(go_sched_pauses_total_gc_seconds_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P95.00%"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(go_sched_pauses_total_gc_seconds_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P99.00%"
    }
   ]
  },
  {
   "title": "/sched/pauses/total/other:seconds",
   "type": "graph",
   "yaxes": [
    { "format": "seconds" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.800000, sum(rate(go_sched_pauses_total_other_seconds_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P80.00%"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(go_sched_pauses_total_other_seconds_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P90.00%"
    },
    {
     "expr": "histogram_quantile(0.950000, sum(rate(go_sched_pauses_total_other_seconds_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P95.00%"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(go_sched_pauses_total_other_seconds_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P99.00%"
    }
   ]
  }
 ]
}
{
 "title": "Sync",
 "panels": [
  {
   "title": "/sync/mutex/wait/total:seconds",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_sync_mutex_wait_total_seconds_total{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "rate: /sync/mutex/wait/total:seconds",
   "type": "graph",
   "yaxes": [
    { "format": "seconds" }
   ],
   "targets": [
    {
     "expr": "sum(rate(go_sync_mutex_wait_total_seconds_total{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}
{
 "title": "CGO",
 "panels": [
  {
   "title": "/cgo/go-to-c-calls:calls",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_cgo_go_to_c_calls_calls_total{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "rate: /cgo/go-to-c-calls:calls",
   "type": "graph",
   "yaxes": [
    { "format": "calls" }
   ],
   "targets": [
    {
     "expr": "sum(rate(go_cgo_go_to_c_calls_calls_total{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}