{
 "title": "Logtail overview",
 "panels": [
  {
   "title": "P50.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_logtail_append_duration_seconds_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "append"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_logtail_send_duration_seconds_bucket{step=\"total\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "send"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_logtail_send_duration_seconds_bucket{step=\"latency\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "send-latency"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_logtail_send_duration_seconds_bucket{step=\"network\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "send-network"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_logtail_apply_duration_seconds_bucket{step=\"apply\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "apply"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_logtail_apply_duration_seconds_bucket{step=\"apply-latency\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "apply-latency"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_logtail_apply_duration_seconds_bucket{step=\"apply-notify\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "apply-notify"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_logtail_apply_duration_seconds_bucket{step=\"apply-notify-latency\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "apply-notify-latency"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_txn_commit_duration_seconds_bucket{type=\"cn-wait-logtail\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "wait-commit-apply"
    }
   ]
  },
  {
   "title": "P80.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_logtail_append_duration_seconds_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "append"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_logtail_send_duration_seconds_bucket{step=\"total\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "send"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_logtail_send_duration_seconds_bucket{step=\"latency\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "send-latency"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_logtail_send_duration_seconds_bucket{step=\"network\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "send-network"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_logtail_apply_duration_seconds_bucket{step=\"apply\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "apply"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_logtail_apply_duration_seconds_bucket{step=\"apply-latency\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "apply-latency"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_logtail_apply_duration_seconds_bucket{step=\"apply-notify\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "apply-notify"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_logtail_apply_duration_seconds_bucket{step=\"apply-notify-latency\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "apply-notify-latency"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_txn_commit_duration_seconds_bucket{type=\"cn-wait-logtail\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "wait-commit-apply"
    }
   ]
  },
  {
   "title": "P90.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_logtail_append_duration_seconds_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "append"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_logtail_send_duration_seconds_bucket{step=\"total\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "send"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_logtail_send_duration_seconds_bucket{step=\"latency\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "send-latency"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_logtail_send_duration_seconds_bucket{step=\"network\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "send-network"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_logtail_apply_duration_seconds_bucket{step=\"apply\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "apply"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_logtail_apply_duration_seconds_bucket{step=\"apply-latency\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "apply-latency"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_logtail_apply_duration_seconds_bucket{step=\"apply-notify\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "apply-notify"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_logtail_apply_duration_seconds_bucket{step=\"apply-notify-latency\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "apply-notify-latency"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_txn_commit_duration_seconds_bucket{type=\"cn-wait-logtail\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "wait-commit-apply"
    }
   ]
  },
  {
   "title": "P99.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_logtail_append_duration_seconds_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "append"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_logtail_send_duration_seconds_bucket{step=\"total\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "send"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_logtail_send_duration_seconds_bucket{step=\"latency\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "send-latency"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_logtail_send_duration_seconds_bucket{step=\"network\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "send-network"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_logtail_apply_duration_seconds_bucket{step=\"apply\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "apply"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_logtail_apply_duration_seconds_bucket{step=\"apply-latency\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "apply-latency"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_logtail_apply_duration_seconds_bucket{step=\"apply-notify\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "apply-notify"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_logtail_apply_duration_seconds_bucket{step=\"apply-notify-latency\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "apply-notify-latency"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_txn_commit_duration_seconds_bucket{type=\"cn-wait-logtail\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "wait-commit-apply"
    }
   ]
  }
 ]
}
{
 "title": "Logtail Queue Status",
 "panels": [
  {
   "title": "CN Received status",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mo_logtail_received_total{type=\"total\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (pod)",
     "legendFormat": "{{ pod }}: total"
    },
    {
     "expr": "sum(rate(mo_logtail_received_total{type=\"subscribe\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (pod)",
     "legendFormat": "{{ pod }}: subscribe"
    },
    {
     "expr": "sum(rate(mo_logtail_received_total{type=\"unsubscribe\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (pod)",
     "legendFormat": "{{ pod }}: unsubscribe"
    },
    {
     "expr": "sum(rate(mo_logtail_received_total{type=\"update\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (pod)",
     "legendFormat": "{{ pod }}: update"
    },
    {
     "expr": "sum(rate(mo_logtail_received_total{type=\"heartbeat\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (pod)",
     "legendFormat": "{{ pod }}: heartbeat"
    }
   ]
  },
  {
   "title": "Queue status",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mo_logtail_queue_size{type=\"send\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"})",
     "legendFormat": "send"
    },
    {
     "expr": "sum(mo_logtail_queue_size{type=\"receive\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"})",
     "legendFormat": "receive"
    },
    {
     "expr": "sum(mo_logtail_queue_size{type=\"apply\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"})",
     "legendFormat": "apply"
    }
   ]
  },
  {
   "title": "Checkpoint logtail",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mo_logtail_load_checkpoint_total{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}
{
 "title": "Logtail size",
 "panels": [
  {
   "title": "Logtail size",
   "type": "graph",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_logtail_bytes_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P50.00%"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_logtail_bytes_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P80.00%"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_logtail_bytes_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P90.00%"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_logtail_bytes_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P99.00%"
    }
   ]
  }
 ]
}
{
 "title": "Logtail load checkpoint",
 "panels": [
  {
   "title": "Logtail load checkpoint",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_logtail_load_checkpoint_duration_seconds_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P50.00%"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_logtail_load_checkpoint_duration_seconds_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P80.00%"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_logtail_load_checkpoint_duration_seconds_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P90.00%"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_logtail_load_checkpoint_duration_seconds_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P99.00%"
    }
   ]
  }
 ]
}
{
 "title": "Logtail collect duration",
 "panels": [
  {
   "title": "pull type phase1 collection duration",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_logtail_pull_collection_phase1_duration_seconds_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P50.00%"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_logtail_pull_collection_phase1_duration_seconds_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P80.00%"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_logtail_pull_collection_phase1_duration_seconds_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P90.00%"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_logtail_pull_collection_phase1_duration_seconds_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P99.00%"
    }
   ]
  },
  {
   "title": "pull type phase2 collection duration",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_logtail_pull_collection_phase2_duration_seconds_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P50.00%"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_logtail_pull_collection_phase2_duration_seconds_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P80.00%"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_logtail_pull_collection_phase2_duration_seconds_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P90.00%"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_logtail_pull_collection_phase2_duration_seconds_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P99.00%"
    }
   ]
  },
  {
   "title": "push type collection duration",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_logtail_push_collection_duration_seconds_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P50.00%"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_logtail_push_collection_duration_seconds_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P80.00%"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_logtail_push_collection_duration_seconds_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P90.00%"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_logtail_push_collection_duration_seconds_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P99.00%"
    }
   ]
  }
 ]
}
{
 "title": "Logtail Transmit counter",
 "panels": [
  {
   "title": "Server Send",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mo_logtail_transmit_total{type=\"server-send\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Client Receive",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mo_logtail_transmit_total{type=\"client-receive\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))"
    }
   ]
  }
 ]
}
{
 "title": "logtail subscription the tn have received",
 "panels": [
  {
   "title": "logtail subscription average increase",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(mo_logtail_subscription_request_total{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "logtail subscription average increase, sensitive",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(mo_logtail_subscription_request_total{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}
{
 "title": "Logtail update partition",
 "panels": [
  {
   "title": "P50.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_logtail_update_partition_duration_seconds_bucket{step=\"enqueue-global-stats\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "enqueue-global-stats"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_logtail_update_partition_duration_seconds_bucket{step=\"get-partition\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "get-partition"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_logtail_update_partition_duration_seconds_bucket{step=\"get-lock\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "get-lock"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_logtail_update_partition_duration_seconds_bucket{step=\"get-catalog\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "get-catalog"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_logtail_update_partition_duration_seconds_bucket{step=\"handle-checkpoint\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "handle-checkpoint"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_logtail_update_partition_duration_seconds_bucket{step=\"consume\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "consume"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_logtail_update_partition_duration_seconds_bucket{step=\"consume-catalog-table\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "consume-catalog-table"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_logtail_update_partition_duration_seconds_bucket{step=\"consume-catalog-table\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "consume-catalog-table"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_logtail_update_partition_duration_seconds_bucket{step=\"consume-one-entry\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "consume-one-entry"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_logtail_update_partition_duration_seconds_bucket{step=\"consume-one-entry-logtailreplay\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "consume-one-entry-logtailreplay"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_logtail_update_partition_duration_seconds_bucket{step=\"consume-one-entry-catalog-cache\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "consume-one-entry-catalog-cache"
    },
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_logtail_update_partition_duration_seconds_bucket{step=\"update-timestamps\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "update-timestamps"
    }
   ]
  },
  {
   "title": "P80.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_logtail_update_partition_duration_seconds_bucket{step=\"enqueue-global-stats\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "enqueue-global-stats"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_logtail_update_partition_duration_seconds_bucket{step=\"get-partition\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "get-partition"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_logtail_update_partition_duration_seconds_bucket{step=\"get-lock\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "get-lock"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_logtail_update_partition_duration_seconds_bucket{step=\"get-catalog\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "get-catalog"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_logtail_update_partition_duration_seconds_bucket{step=\"handle-checkpoint\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "handle-checkpoint"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_logtail_update_partition_duration_seconds_bucket{step=\"consume\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "consume"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_logtail_update_partition_duration_seconds_bucket{step=\"consume-catalog-table\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "consume-catalog-table"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_logtail_update_partition_duration_seconds_bucket{step=\"consume-catalog-table\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "consume-catalog-table"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_logtail_update_partition_duration_seconds_bucket{step=\"consume-one-entry\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "consume-one-entry"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_logtail_update_partition_duration_seconds_bucket{step=\"consume-one-entry-logtailreplay\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "consume-one-entry-logtailreplay"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_logtail_update_partition_duration_seconds_bucket{step=\"consume-one-entry-catalog-cache\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "consume-one-entry-catalog-cache"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_logtail_update_partition_duration_seconds_bucket{step=\"update-timestamps\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "update-timestamps"
    }
   ]
  },
  {
   "title": "P90.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_logtail_update_partition_duration_seconds_bucket{step=\"enqueue-global-stats\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "enqueue-global-stats"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_logtail_update_partition_duration_seconds_bucket{step=\"get-partition\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "get-partition"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_logtail_update_partition_duration_seconds_bucket{step=\"get-lock\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "get-lock"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_logtail_update_partition_duration_seconds_bucket{step=\"get-catalog\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "get-catalog"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_logtail_update_partition_duration_seconds_bucket{step=\"handle-checkpoint\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "handle-checkpoint"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_logtail_update_partition_duration_seconds_bucket{step=\"consume\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "consume"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_logtail_update_partition_duration_seconds_bucket{step=\"consume-catalog-table\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "consume-catalog-table"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_logtail_update_partition_duration_seconds_bucket{step=\"consume-catalog-table\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "consume-catalog-table"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_logtail_update_partition_duration_seconds_bucket{step=\"consume-one-entry\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "consume-one-entry"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_logtail_update_partition_duration_seconds_bucket{step=\"consume-one-entry-logtailreplay\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "consume-one-entry-logtailreplay"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_logtail_update_partition_duration_seconds_bucket{step=\"consume-one-entry-catalog-cache\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "consume-one-entry-catalog-cache"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_logtail_update_partition_duration_seconds_bucket{step=\"update-timestamps\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "update-timestamps"
    }
   ]
  },
  {
   "title": "P99.000000 time",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_logtail_update_partition_duration_seconds_bucket{step=\"enqueue-global-stats\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "enqueue-global-stats"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_logtail_update_partition_duration_seconds_bucket{step=\"get-partition\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "get-partition"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_logtail_update_partition_duration_seconds_bucket{step=\"get-lock\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "get-lock"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_logtail_update_partition_duration_seconds_bucket{step=\"get-catalog\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "get-catalog"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_logtail_update_partition_duration_seconds_bucket{step=\"handle-checkpoint\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "handle-checkpoint"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_logtail_update_partition_duration_seconds_bucket{step=\"consume\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "consume"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_logtail_update_partition_duration_seconds_bucket{step=\"consume-catalog-table\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "consume-catalog-table"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_logtail_update_partition_duration_seconds_bucket{step=\"consume-catalog-table\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "consume-catalog-table"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_logtail_update_partition_duration_seconds_bucket{step=\"consume-one-entry\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "consume-one-entry"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_logtail_update_partition_duration_seconds_bucket{step=\"consume-one-entry-logtailreplay\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "consume-one-entry-logtailreplay"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_logtail_update_partition_duration_seconds_bucket{step=\"consume-one-entry-catalog-cache\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "consume-one-entry-catalog-cache"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_logtail_update_partition_duration_seconds_bucket{step=\"update-timestamps\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))  by (le))",
     "legendFormat": "update-timestamps"
    }
   ]
  }
 ]
}