{
 "title": "Proxy Connection",
 "panels": [
  {
   "title": "Connect Counter",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mo_proxy_connect_counter{type=\"accepted\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))",
     "legendFormat": "accepted"
    },
    {
     "expr": "sum(rate(mo_proxy_connect_counter{type=\"current\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))",
     "legendFormat": "current"
    },
    {
     "expr": "sum(rate(mo_proxy_connect_counter{type=\"success\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))",
     "legendFormat": "success"
    },
    {
     "expr": "sum(rate(mo_proxy_connect_counter{type=\"route-fail\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))",
     "legendFormat": "route-fail"
    },
    {
     "expr": "sum(rate(mo_proxy_connect_counter{type=\"common-fail\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))",
     "legendFormat": "common-fail"
    },
    {
     "expr": "sum(rate(mo_proxy_connect_counter{type=\"retry\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))",
     "legendFormat": "retry"
    },
    {
     "expr": "sum(rate(mo_proxy_connect_counter{type=\"select\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))",
     "legendFormat": "select"
    },
    {
     "expr": "sum(rate(mo_proxy_connect_counter{type=\"reject\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))",
     "legendFormat": "reject"
    }
   ]
  },
  {
   "title": "Disconnect Counter",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mo_proxy_disconnect_counter{type=\"server\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))",
     "legendFormat": "server"
    },
    {
     "expr": "sum(rate(mo_proxy_disconnect_counter{type=\"client\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))",
     "legendFormat": "client"
    }
   ]
  }
 ]
}
{
 "title": "Connection transfer duration",
 "panels": [
  {
   "title": "connection transfer duration",
   "type": "graph",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.500000, sum(rate(mo_proxy_connection_transfer_duration_seconds_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P50.00%"
    },
    {
     "expr": "histogram_quantile(0.800000, sum(rate(mo_proxy_connection_transfer_duration_seconds_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P80.00%"
    },
    {
     "expr": "histogram_quantile(0.900000, sum(rate(mo_proxy_connection_transfer_duration_seconds_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P90.00%"
    },
    {
     "expr": "histogram_quantile(0.990000, sum(rate(mo_proxy_connection_transfer_duration_seconds_bucket{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by (le))",
     "legendFormat": "P99.00%"
    }
   ]
  }
 ]
}
{
 "title": "Proxy Transfer",
 "panels": [
  {
   "title": "Connection Transfer Counter",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mo_proxy_connection_transfer_counter{type=\"success\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))",
     "legendFormat": "success"
    },
    {
     "expr": "sum(rate(mo_proxy_connection_transfer_counter{type=\"fail\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))",
     "legendFormat": "fail"
    },
    {
     "expr": "sum(rate(mo_proxy_connection_transfer_counter{type=\"abort\",matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))",
     "legendFormat": "abort"
    }
   ]
  },
  {
   "title": "Backend Server Drain Counter",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mo_proxy_drain_counter{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))"
    }
   ]
  }
 ]
}
{
 "title": "Proxy Others State",
 "panels": [
  {
   "title": "Available Backend Server Num",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mo_proxy_available_backend_server_num{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Transfer Queue Size",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mo_proxy_transfer_queue_size{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Connections Need To Transfer",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mo_proxy_connections_need_to_transfer{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Connections In Transfer Intent State",
   "type": "graph",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mo_proxy_connections_transfer_intent{matrixone_cloud_main_cluster=~\"$physicalCluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval]))"
    }
   ]
  }
 ]
}