{
 "title": "MO-OB Alert Info",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "ALERTNAME",
    "label": "Alert Name",
    "query": {
     "query": "label_values(ALERTS, alertname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Alert Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count by(namespace, alertname, pod) (ALERTS{alertname=\"$ALERTNAME\"})"
    }
   ]
  },
  {
   "title": "Alert History Query",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "ALERTS{alertname=\"$ALERTNAME\"}"
    }
   ]
  },
  {
   "title": "Current Active Alerts",
   "type": "alertlist",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 16 },
   "targets": [
    { "expr": "ALERTS" }
   ]
  }
 ]
}