apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-web-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
data:
  alertmanager-web-config.yaml: {{ include "alertmanager.web" . | b64enc }}