apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-auth-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
data:
  username: {{ .Values.secretValue.alertmanager.alertmanager_web_auth_user | b64enc }}
  password: {{ .Values.secretValue.alertmanager.alertmanager_web_auth_password | b64enc }}
type: Opaque