apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-loki-credentials
data:
  alertmanager-loki-credentials: {{ printf "%s:%s" .Values.secretValue.alertmanager.alertmanager_web_auth_user .Values.secretValue.alertmanager.alertmanager_web_auth_password | b64enc | b64enc }}
type: Opaque
