groups:
- name: cos.rules
  rules:
  - alert: RootClusterDown
    expr: sum(mo_cluster_up{cluster=~"freetier-01", job="kubernetes-service-endpoints"}) by (cluster) < 1
    for: 2m
    labels:
      severity: critical
      serviceScope: mo-cluster
      alertOwner: aylei
      alertTeam: "Orch Team"
    annotations:
      summary: root cluster {{ $labels.cluster }} down
  - alert: ClusterCreationTooLong
    expr: (time() - mo_cluster_cn_creation_time{phase=~"Creating|Pending", job="kubernetes-service-endpoints", cluster_type=~"serverless_charged|serverless_free"}) > 300
    for: 0m
    labels:
      severity: critical
      serviceScope: mo-cluster
      alertOwner: aylei
      alertTeam: "Orch Team"
    annotations:
      summary: serverless cluster {{ $labels.cluster }} creation too long, {{ $value }} seconds
  - alert: ReservedClusterCreationTooLong
    expr: (time() - mo_cluster_cn_creation_time{phase=~"Creating|Pending", job="kubernetes-service-endpoints", cluster_type="reserved"}) > 1200 # 20 minutes
    for: 0m
    labels:
      severity: critical
      serviceScope: mo-cluster
      alertOwner: lr90
      alertTeam: "Orch Team"
    annotations:
      summary: reserved cluster {{ $labels.cluster }} creation too long, {{ $value }} seconds
