apiVersion: v2
name: mo-ob-private
description: mo-ob-private's Helm chart for Kubernetes
type: application
version: 1.0.1
appVersion: 0.9.0
dependencies:
- condition: mo-ob-opensource.enabled
  name: mo-ob-opensource
  repository: https://matrixorigin.github.io/observability-charts
  version: 1.0.7
- condition: mo-ruler-stack.enabled
  name: mo-ruler-stack
  repository: https://matrixorigin.github.io/observability-charts
  version: 1.0.4

