mo-ob-opensource:
  alloy: {}
  promtail:
    ## 这个不确定能否修改，需要验证一下
    podSecurityContext:
      runAsUser: 1000670000
      runAsGroup: 1000670000
  loki:
    loki:
      podSecurityContext:
        fsGroup: 1000670000
        runAsGroup: 1000670000
        runAsNonRoot: true
        runAsUser: 1000670000
  kube-prometheus-stack:
    kube-state-metrics:
      securityContext:
        enabled: true
        runAsGroup: 1000670000
        runAsUser: 1000670000
        fsGroup: 1000670000
    prometheus-node-exporter:
      securityContext:
        fsGroup: 1000670000
        runAsGroup: 1000670000
        runAsNonRoot: true
        runAsUser: 1000670000
    prometheusOperator:
      securityContext:
        fsGroup: 1000670000
        runAsGroup: 1000670000
        runAsNonRoot: true
        runAsUser: 1000670000
    prometheus:
      prometheusSpec:
        securityContext:
          runAsGroup: 1000670000
          runAsNonRoot: true
          runAsUser: 1000670000
          fsGroup: 1000670000

mo-ruler-stack:
  alertmanagerWebhookAdapter: {}
  alertmanager: {}
  grafana: {}