mo-ob-opensource:
  alloy: {}
  promtail:
    ## 这个不确定能否修改，需要验证一下
    podSecurityContext:
      runAsUser: 0
      runAsGroup: 0
  loki:
    loki:
      podSecurityContext:
        fsGroup: 10001
        runAsGroup: 10001
        runAsNonRoot: true
        runAsUser: 1000
  kube-prometheus-stack:
    kube-state-metrics:
      securityContext:
        enabled: true
        runAsGroup: 65534
        runAsUser: 65534
        fsGroup: 65534
    prometheus-node-exporter:
      securityContext:
        fsGroup: 65534
        runAsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
    prometheusOperator:
      securityContext:
        fsGroup: 65534
        runAsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
    prometheus:
      prometheusSpec:
        securityContext:
          runAsGroup: 2000
          runAsNonRoot: true
          runAsUser: 1000
          fsGroup: 200

mo-ruler-stack:
  alertmanagerWebhookAdapter: {}
  alertmanager: {}
  grafana: {}