mo-ob-opensource:
  enabled: true

  alloy:
    enabled: true
    image:
      registry: "docker.io"
      repository: grafana/alloy
      tag: v1.3.1
    configReloader:
      enabled: false
    alloy:
      resources: 
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 200m
          memory: 200Mi
  promtail:
    image:
      registry: docker.io
      repository: grafana/promtail
      tag: "2.8.4"
    enabled: true
    resources:
      limits:
        cpu: "200m"
        memory: "200Mi"
      requests:
        cpu: "10m"
        memory: "20Mi"
  loki:
    lokiCanary:
      enabled: false
    sidecar: 
      image:
        repository: kiwigrid/k8s-sidecar
        tag: 1.27.5
    image:
      registry: docker.io
      repository: grafana/loki
      tag: "3.2.0"
    enabled: true
    tableManager:
      enabled: true
      # retention related issue: https://github.com/matrixone-cloud/observability/issues/86
      retention_deletes_enabled: true
      retention_period: 720h
    # loki monolithic mode
    # singleBinary:
    #   replicas: 2
    loki:
      # disable log alert in paivate env
      rulerConfig: 
        storage: 
          type: ""  
      commonConfig:
        replication_factor: 1
      storage_config:
        object_prefix: loki-controlplane
      storage:
        bucketNames:
          chunks: test-bucket
        type: s3
        s3:
          endpoint: minio.loki-tenant
          accessKeyId: obtest-access
          secretAccessKey: obtest-secret
          s3ForcePathStyle: true
          insecure: true
      schemaConfig:
        configs:
          - from: "2024-01-01"
            index:
              period: 24h
              prefix: index_
            object_store: s3
            schema: v13
            store: tsdb
    write:
      # -- Number of replicas for the write
      replicas: 1
      persistence:
        enableStatefulSetAutoDeletePVC: false
        size: 10Gi
        storageClass: 
      resources:
        requests:
          memory: "1Gi"
          cpu: "250m"
        limits:
          memory: "1Gi"
          cpu: "1000m"

    read:
      replicas: 1
      persistence:
        enableStatefulSetAutoDeletePVC: true
        size: 10Gi
        storageClass: 
      resources:
        requests:
          memory: "3Gi"
          cpu: "250m"
        limits:
          memory: "3Gi"
          cpu: "1000m"

    backend:
      replicas: 1
      persistence:
        enableStatefulSetAutoDeletePVC: true
        size: 10Gi
        storageClass: 
      resources:
        requests:
          memory: "250Mi"
          cpu: "200m"
        limits:
          memory: "250Mi"
          cpu: "200m"

    # Configuration for the gateway
    gateway:
      image:
        registry: docker.io
        repository: nginxinc/nginx-unprivileged
        tag: 1.27-alpine
      enabled: true
      replicas: 1
      resources:
        requests:
          memory: "250Mi"
          cpu: "250m"
        limits:
          memory: "1Gi"
          cpu: "1000m"

  kube-prometheus-stack:
    enabled: true
    
    prometheus-node-exporter: 
      image:
        registry: quay.io
        repository: prometheus/node-exporter
        tag: v1.5.0
      enabled: true
      resources: 
        limits: 
          cpu:    "200m"
          memory: "100Mi"
        requests: 
          cpu:    "10m"
          memory: "20Mi"
    
    prometheusOperator:
      image: 
        registry: quay.io
        repository: prometheus-operator/prometheus-operator
        tag: v0.63.0
      prometheusConfigReloader: 
        image:
          registry: quay.io
          repository: prometheus-operator/prometheus-config-reloader
          # if not set appVersion field from Chart.yaml is used
          tag: v0.63.0
      admissionWebhooks: 
        enabled: false
        patch: 
          enabled: false
      resources:
        limits:
          cpu: "200m"
          memory: "400Mi"
        requests:
          cpu: "100m"
          memory: "400Mi"
    
    prometheus:
      prometheusSpec:
        image:
          registry: quay.io
          repository: prometheus/prometheus
          tag: v2.42.0
        retention: 21d
        externalLabels:
          clusterDetail: mo-ob-private-cluster
        resources:
          limits:
            cpu: 1000m
            memory: "2Gi"
          requests:
            cpu: 1000m
            memory: "2Gi"
        # [必要]根据部署的云厂商选择存储配置
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: standard
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 40Gi
        additionalScrapeConfigs: 
          - job_name: minio-cluster
            # metrics_path: /minio/v2/metrics/cluster
            scheme: http
            # static_configs:
            # - targets: [minio.mo-ob.svc.cluster.local]
            metrics_path: /minio/v2/metrics/cluster
            honor_labels: true
            kubernetes_sd_configs:
              - role: endpoints
            relabel_configs:
              - source_labels: [__meta_kubernetes_service_labelpresent_v1_min_io_tenant]
                action: keep
                regex: "true"
              - source_labels: [__meta_kubernetes_service_name]
                action: keep
                regex: "minio"
              - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
                action: replace
                target_label: __metrics_path__
                regex: (.+)
              - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
                action: replace
                target_label: __address__
                regex: (.+?)(?::\d+)?;(\d+)
                replacement: $1:$2
              - action: labelmap
                regex: __meta_kubernetes_service_annotation_prometheus_io_param_(.+)
                replacement: __param_$1
              - action: labelmap
                regex: __meta_kubernetes_pod_label_(.+)
              - action: labelmap
                regex: __meta_kubernetes_service_label_(.+)
              - source_labels: [__meta_kubernetes_namespace]
                action: replace
                target_label: namespace
              - source_labels: [__meta_kubernetes_service_name]
                action: replace
                target_label: service
              - source_labels: [__meta_kubernetes_pod_node_name]
                action: replace
                target_label: node
              - source_labels: [__meta_kubernetes_pod_name]
                action: replace
                target_label: pod
          
          - job_name: minio-bucket
            metrics_path: /minio/v2/metrics/bucket
            scheme: http
            honor_labels: true
            kubernetes_sd_configs:
              - role: endpoints
            relabel_configs:
              - source_labels: [__meta_kubernetes_service_labelpresent_v1_min_io_tenant]
                action: keep
                regex: "true"
              - source_labels: [__meta_kubernetes_service_name]
                action: keep
                regex: "minio"
              - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
                action: replace
                target_label: __metrics_path__
                regex: (.+)
              - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
                action: replace
                target_label: __address__
                regex: (.+?)(?::\d+)?;(\d+)
                replacement: $1:$2
              - action: labelmap
                regex: __meta_kubernetes_service_annotation_prometheus_io_param_(.+)
                replacement: __param_$1
              - action: labelmap
                regex: __meta_kubernetes_pod_label_(.+)
              - action: labelmap
                regex: __meta_kubernetes_service_label_(.+)
              - source_labels: [__meta_kubernetes_namespace]
                action: replace
                target_label: namespace
              - source_labels: [__meta_kubernetes_service_name]
                action: replace
                target_label: service
              - source_labels: [__meta_kubernetes_pod_node_name]
                action: replace
                target_label: node
              - source_labels: [__meta_kubernetes_pod_name]
                action: replace
                target_label: pod

          - job_name: matrixone-cluster
            metrics_path: /metrics
            scheme: http
            honor_labels: true
            kubernetes_sd_configs:
              - role: endpoints
            relabel_configs:
              - source_labels: [__meta_kubernetes_pod_labelpresent_matrixorigin_io_namespace]
                action: keep
                regex: "true"
              - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
                action: replace
                target_label: __metrics_path__
                regex: (.+)
              - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
                action: replace
                target_label: __address__
                regex: (.+?)(?::\d+)?;(\d+)
                replacement: $1:$2
              - action: labelmap
                regex: __meta_kubernetes_service_annotation_prometheus_io_param_(.+)
                replacement: __param_$1
              - action: labelmap
                regex: __meta_kubernetes_pod_label_(.+)
              - action: labelmap
                regex: __meta_kubernetes_service_label_(.+)
              - source_labels: [__meta_kubernetes_namespace]
                action: replace
                target_label: namespace
              - source_labels: [__meta_kubernetes_service_name]
                action: replace
                target_label: service
              - source_labels: [__meta_kubernetes_pod_node_name]
                action: replace
                target_label: node
              - source_labels: [__meta_kubernetes_pod_name]
                action: replace
                target_label: pod

          - job_name: 'kubernetes-service-endpoints'
            honor_labels: true
            kubernetes_sd_configs:
              - role: endpoints
            relabel_configs:
              - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
                action: keep
                regex: true
              - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape_slow]
                action: drop
                regex: true
              - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
                action: replace
                target_label: __scheme__
                regex: (https?)
              - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
                action: replace
                target_label: __metrics_path__
                regex: (.+)
              - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
                action: replace
                target_label: __address__
                regex: (.+?)(?::\d+)?;(\d+)
                replacement: $1:$2
              - action: labelmap
                regex: __meta_kubernetes_service_annotation_prometheus_io_param_(.+)
                replacement: __param_$1
              - action: labelmap
                regex: __meta_kubernetes_pod_label_(.+)
              - action: labelmap
                regex: __meta_kubernetes_service_label_(.+)
              - source_labels: [__meta_kubernetes_namespace]
                action: replace
                target_label: namespace
              - source_labels: [__meta_kubernetes_service_name]
                action: replace
                target_label: service
              - source_labels: [__meta_kubernetes_pod_node_name]
                action: replace
                target_label: node
              - source_labels: [__meta_kubernetes_pod_name]
                action: replace
                target_label: pod

          - job_name: 'kubernetes-service-endpoints-slow'
            honor_labels: true

            scrape_interval: 5m
            scrape_timeout: 30s

            kubernetes_sd_configs:
              - role: endpoints

            relabel_configs:
              - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape_slow]
                action: keep
                regex: true
              - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
                action: replace
                target_label: __scheme__
                regex: (https?)
              - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
                action: replace
                target_label: __metrics_path__
                regex: (.+)
              - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
                action: replace
                target_label: __address__
                regex: (.+?)(?::\d+)?;(\d+)
                replacement: $1:$2
              - action: labelmap
                regex: __meta_kubernetes_service_annotation_prometheus_io_param_(.+)
                replacement: __param_$1
              - action: labelmap
                regex: __meta_kubernetes_pod_label_(.+)
              - action: labelmap
                regex: __meta_kubernetes_service_label_(.+)
              - source_labels: [__meta_kubernetes_namespace]
                action: replace
                target_label: namespace
              - source_labels: [__meta_kubernetes_service_name]
                action: replace
                target_label: service
              - source_labels: [__meta_kubernetes_pod_node_name]
                action: replace
                target_label: node
              - source_labels: [__meta_kubernetes_pod_name]
                action: replace
                target_label: pod

          - job_name: "moob-application"
            honor_labels: true
            kubernetes_sd_configs:
              - role: endpoints
            relabel_configs:
              - action: keep
                regex: "mo-ob"
                source_labels:
                - __meta_kubernetes_namespace
              - source_labels:
                - __meta_kubernetes_endpoints_label_need_metrics
                action: keep
                regex: true
              - action: labelmap
                regex: __meta_kubernetes_pod_label_(.+)
              - action: labelmap
                regex: __meta_kubernetes_endpoints_label_(.+)
              - action: replace
                source_labels:
                - __meta_kubernetes_namespace
                target_label: namespace
              - action: replace
                source_labels:
                - __meta_kubernetes_service_name
                target_label: service
              - action: replace
                source_labels:
                - __meta_kubernetes_pod_node_name
                target_label: node
              - action: replace
                source_labels: [__meta_kubernetes_pod_name]
                target_label: pod
    
    kube-state-metrics:
      enabled: true
      image:
        registry: registry.k8s.io
        repository: kube-state-metrics/kube-state-metrics
        tag: v2.8.2
      prometheus:
        monitor:
          enabled: ture

mo-ruler-stack:
  enabled: true
  moRuler:
    enabled: false

  # webhook adapter for alertmanger to send alert to wecom
  alertmanagerWebhookAdapter:
    enabled: false
    image:
      repository: ez4bruce3280/alertmanager-webhook-adapter
      tag: v1.1.7

  alertmanager:
    image:
      repository: quay.io/prometheus/alertmanager
      pullPolicy: IfNotPresent
      tag: v0.27.0
    enabled: true
    persistence:
      enabled: false
    config:
      global:
        resolve_timeout: 5m
        smtp_from: "it@matrixorigin.cn"
        smtp_hello: "smtp.exmail.qq.com:465"
        smtp_smarthost: "smtp.exmail.qq.com:465"
        smtp_auth_username: "it@matrixorigin.cn"
        smtp_auth_password_file: "/tmp/alertmanager-email-smtp/smtp-authorization"
        smtp_require_tls: false
      route:
        group_by: ["alertname"] # 分组标签
        group_wait: 10s # 告警等待时间。告警产生后等待10s，如果有同组告警一起发出
        group_interval: 10s # 两组告警的间隔时间
        repeat_interval: 1d # 重复告警的间隔时间，可减少相同邮件的发送频率
        receiver: "null"
        # routes: 
      receivers:
        - name: "null"

    extraSecretMounts:
      # kubectl -n mo-ob create secret generic alertmanager-email-secret --from-literal=smtp-authorization=[your-smtp-password]
      - name: smtp-authorization
        mountPath: /tmp/alertmanager-email-smtp
        subPath: ""
        secretName: alertmanager-email-secret
        readOnly: true
      - name: web-config
        mountPath: /tmp/alertmanager-web-config
        subPath: ""
        secretName: alertmanager-web-config
        readOnly: true
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 32Mi

  grafana:
    image:
      repository: docker.io/grafana/grafana
      tag: 10.1.6
    initChownData: 
      image:
        repository: docker.io/library/busybox
        tag: 1.31.1
    sidecar: 
      image:
        repository: quay.io/kiwigrid/k8s-sidecar
        tag: 1.25.1
      
    replicas: 1
    enabled: true
    resources: 
      limits: 
        cpu:    "500m"
        memory: "1Gi"
      requests: 
        cpu:    "200m"
        memory: "1Gi"
    
    persistence: 
      enabled:          true
      type:             "statefulset"
      storageClassName: 
      size:             "5Gi"
    
    # static passwd
    adminUser: admin
    adminPassword: admin
    admin:
      existingSecret: ""
    
      grafana.ini:
      auth.generic_oauth:
        enabled: false
    
    service:
      enabled: true
      type: NodePort
      targetPort: 3000
      labels: {}
      portName: service
      # Adds the appProtocol field to the service. This allows to work with istio protocol selection. Ex: "http" or "tcp"
      appProtocol: ""
