{{- if not .Values.serviceAccount.kubeStateMetrics.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default "mo-ob-opensource-kube-state-metrics" .Values.serviceAccount.kubeStateMetrics.name }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
