apiVersion: v1
kind: ConfigMap
metadata:
  name: mo-vm-datasource
  labels:
    app: victoriametrics
    grafana_datasource: "1"
data:
  vm-datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: MO-VictoriaMetrics
      type: prometheus
      uid: victoriametrics
      url: http://vmsingle-{{ .Values.vmDatasource.vmService }}:8429
      access: proxy
