{
 "title": "Cluster / Overview",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "mo_cluster", "label": "Matrixone Cluster", "query": "mysql" },
   { "name": "mo_prom", "label": "Observability", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "MO Cluster",
    "query": {
     "query": "label_values(mo_cluster_info,main_cluster)"
    }
   },
   {
    "name": "interval",
    "label": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Cluster Properties", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Created Time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "api_iott",
     "rawSql": "SELECT created_time FROM mo_catalog.mo_tables WHERE relname = 'mo_account' LIMIT 1;"
    }
   ]
  },
  {
   "title": "Matrixone Version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "dataset": "api_iott", "rawSql": "SELECT version();" }
   ]
  },
  {
   "title": "Resource Nodes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "dataset": "api_iott", "rawSql": "show backend servers;" }
   ]
  },
  {
   "title": "Accounts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "api_iott",
     "rawSql": "SELECT COUNT(*) FROM mo_catalog.mo_account;"
    }
   ]
  },
  { "title": "Cluster Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Alerts",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "count by(alertname) (ALERTS{alertstate=~\"firing\"})"
    }
   ]
  },
  { "title": "Firing Alerts", "type": "alertlist", "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 } },
  { "title": "Cluster Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Cluster CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum (rate (container_cpu_usage_seconds_total{image!=\"\"}[1m])) / sum (machine_cpu_cores)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Used Cores",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage Growth",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum (rate (container_cpu_usage_seconds_total{image!=\"\"}[1m])) / sum (machine_cpu_cores)) * 100"
    }
   ]
  },
  {
   "title": "Max Capacity Cores",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": " sum (machine_cpu_cores)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Cluster Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (\n  sum(container_memory_usage_bytes{container!=\"\"})\n    /\n  sum(kube_node_status_capacity{resource=\"memory\"})\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage Growth",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (\n  sum(container_memory_usage_bytes{container!=\"\"})\n    /\n  sum(kube_node_status_capacity{resource=\"memory\"})\n)"
    }
   ]
  },
  {
   "title": "Memory Max Capacity",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{resource=\"memory\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Shared Storage Usage",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(topk(1, sum(minio_cluster_capacity_usable_total_bytes{job=~\".*minio.*\"}) by (instance)) - topk(1, sum(minio_cluster_capacity_usable_free_bytes{job=~\".*minio.*\"}) by (instance)))/topk(1, sum(minio_cluster_capacity_usable_total_bytes{job=~\".*minio.*\"}) by (instance)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Shared Storage Used",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, sum(minio_cluster_capacity_usable_total_bytes{job=~\".*minio.*\"}) by (instance)) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Shared Storage Usage Growth",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(topk(1, sum(minio_cluster_capacity_usable_total_bytes{job=~\".*minio.*\"}) by (instance)) - topk(1, sum(minio_cluster_capacity_usable_free_bytes{job=~\".*minio.*\"}) by (instance)))/topk(1, sum(minio_cluster_capacity_usable_total_bytes{job=~\".*minio.*\"}) by (instance)) * 100"
    }
   ]
  },
  {
   "title": "Shared Storage Max Capacity",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, sum(minio_cluster_capacity_usable_total_bytes{job=~\".*minio.*\"}) by (instance)) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Network Received",
   "type": "stat",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_bytes_total{job=\"kubernetes-service-endpoints\"}[$__rate_interval]))*8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Received Trends",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 6, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_bytes_total{job=\"kubernetes-service-endpoints\"}[$__rate_interval]))*8",
     "legendFormat": "{{device}} - Receive"
    }
   ]
  },
  {
   "title": "Current Network Transmitted",
   "type": "stat",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(node_network_transmit_bytes_total{job=\"kubernetes-service-endpoints\"}[$__rate_interval]))*8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Transmitted Trends",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 6, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(irate(node_network_transmit_bytes_total{job=\"kubernetes-service-endpoints\"}[$__rate_interval]))*8",
     "legendFormat": "{{device}} - Transmit"
    }
   ]
  },
  { "title": "Databases", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 } },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 78 },
   "targets": [
    {
     "expr": "sum(server_connections{matrixone_cloud_main_cluster=~\"$cluster\"}) by (account)",
     "legendFormat": "{{account}}-{{pod}}"
    }
   ]
  },
  {
   "title": "TPS",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(sql_transaction_total{ matrixone_cloud_main_cluster=~\"$cluster\"}[$interval])) by (account)",
     "legendFormat": "{{account}}"
    },
    {
     "expr": "sum(rate(sql_transaction_errors{ matrixone_cloud_main_cluster=~\"$cluster\"}[$interval])) by (account, pod)",
     "legendFormat": "{{account}}-{{pod}}-ERR"
    }
   ]
  }
 ]
}