{
 "title": "Resource / Nodes",
 "tags": [
  "linux",
  "node-exporter"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "kube_node",
    "query": {
     "query": "label_values(kube_node_info,node)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\", node=\"$kube_node\"},instance)"
    }
   },
   {
    "name": "diskdevices",
    "query": "[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+"
   }
  ]
 },
 "panels": [
  { "title": "Current Cluster Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum (rate (container_cpu_usage_seconds_total{image!=\"\"}[1m])) / sum (machine_cpu_cores)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (\n  sum(container_memory_usage_bytes{container!=\"\"})\n    /\n  sum(kube_node_status_capacity{resource=\"memory\"})\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Shared Storage Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(topk(1, sum(minio_cluster_capacity_usable_total_bytes{job=~\".*minio.*\"}) by (instance)) - topk(1, sum(minio_cluster_capacity_usable_free_bytes{job=~\".*minio.*\"}) by (instance)))/topk(1, sum(minio_cluster_capacity_usable_total_bytes{job=~\".*minio.*\"}) by (instance)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Network Received",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_bytes_total{job=\"kubernetes-service-endpoints\"}[$__rate_interval]))*8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Network Transmitted",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(node_network_transmit_bytes_total{job=\"kubernetes-service-endpoints\"}[$__rate_interval]))*8",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Current Node Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(sum by(node) (rate(container_cpu_usage_seconds_total{image!=\"\"}[$__interval])) * 100) / sum by(node) (machine_cpu_cores)"
    },
    {
     "expr": "100 * (\n  sum by(node) (container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", container!=\"\", image!=\"\"}) \n    /\n  sum by(node)(kube_node_status_capacity{resource=\"memory\"})\n)"
    },
    {
     "expr": "(sum by (node) (node_filesystem_size_bytes{job=\"$job\",device!~'rootfs'}) - sum by (node) (node_filesystem_avail_bytes{job=\"$job\",device!~'rootfs'})) / sum by (node) (node_filesystem_size_bytes{job=\"$job\",device!~'rootfs'})*100"
    },
    {
     "expr": "sum(irate(node_network_receive_bytes_total{job=\"kubernetes-service-endpoints\"}[$__rate_interval]))by(node)*8"
    },
    {
     "expr": "sum(irate(node_network_transmit_bytes_total{job=\"kubernetes-service-endpoints\"}[$__rate_interval]))by(node)*8"
    }
   ]
  },
  { "title": "CPU Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Node CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum (rate (container_cpu_usage_seconds_total{image!=\"\",node=\"$kube_node\"}[1m])) / sum (machine_cpu_cores{node=\"$kube_node\"})) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Used Cores",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",node=\"$kube_node\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(\n  (1 - sum without (mode) (rate(node_cpu_seconds_total{job=\"$job\", mode=~\"idle|iowait|steal\", instance=\"$instance\"}[$__rate_interval])))\n/ ignoring(cpu) group_left\n  count without (cpu, mode) (node_cpu_seconds_total{job=\"$job\", mode=\"idle\", instance=\"$instance\"})\n)\n",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "Max Capacity Cores",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " sum (machine_cpu_cores{node=\"$kube_node\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage Growth / cores",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{node=\"$kube_node\"}) by (namespace)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{ node=\"$kube_node\",resource=\"cpu\"})",
     "legendFormat": "quota - requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{ node=\"$kube_node\",resource=\"cpu\"})",
     "legendFormat": "quota - limits"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{node=\"$kube_node\"}) by (namespace) / sum(kube_pod_container_resource_limits{node=\"$kube_node\",resource=\"cpu\"}) by (namespace)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{node=\"$kube_node\"}) by (namespace)"
    }
   ]
  },
  { "title": "Memory Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Node Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (\n  sum(container_memory_usage_bytes{container!=\"\",node=\"$kube_node\"})\n    /\n  sum(kube_node_status_capacity{resource=\"memory\",node=\"$kube_node\"})\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container!=\"\",node=\"$kube_node\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(\n  node_memory_MemTotal_bytes{job=\"$job\", instance=\"$instance\"}\n-\n  node_memory_MemFree_bytes{job=\"$job\", instance=\"$instance\"}\n-\n  node_memory_Buffers_bytes{job=\"$job\", instance=\"$instance\"}\n-\n  node_memory_Cached_bytes{job=\"$job\", instance=\"$instance\"}\n)\n",
     "legendFormat": "memory used"
    },
    {
     "expr": "node_memory_Buffers_bytes{job=\"kubernetes-service-endpoints\", instance=\"$instance\"}",
     "legendFormat": "memory buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{job=\"kubernetes-service-endpoints\", instance=\"$instance\"}",
     "legendFormat": "memory cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"kubernetes-service-endpoints\", instance=\"$instance\"}",
     "legendFormat": "memory free"
    }
   ]
  },
  {
   "title": "Memory Max Capacity",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{resource=\"memory\",node=\"$kube_node\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage (w/o cache)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", node=\"$kube_node\", container!=\"\", image!=\"\"}) by (namespace)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "type": "table-old",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", node=\"$kube_node\",container!=\"\", image!=\"\"}) by (namespace)"
    },
    {
     "expr": "sum(container_memory_rss{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\",  node=\"$kube_node\",container!=\"\"}) by (namespace)"
    },
    {
     "expr": "sum(container_memory_cache{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", node=\"$kube_node\",container!=\"\"}) by (namespace)"
    },
    {
     "expr": "sum(container_memory_swap{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", node=\"$kube_node\",container!=\"\"}) by (namespace)"
    }
   ]
  },
  { "title": "Disk Space Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "Node Disk Space Usage",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (node) (node_filesystem_size_bytes{job=\"$job\",node=\"$kube_node\",device!~'rootfs'}) - sum by (node) (node_filesystem_avail_bytes{job=\"$job\",node=\"$kube_node\",device!~'rootfs'})) / sum by (node) (node_filesystem_size_bytes{job=\"$job\",node=\"$kube_node\",device!~'rootfs'})*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (node) (node_filesystem_size_bytes{job=\"$job\",node=\"$kube_node\",device!~'rootfs'}) - sum by (node) (node_filesystem_avail_bytes{job=\"$job\",node=\"$kube_node\",device!~'rootfs'}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max by (mountpoint) (node_filesystem_size_bytes{job=\"$job\", instance=\"$instance\", fstype!=\"\", mountpoint!=\"\"})\n"
    },
    {
     "expr": "max by (mountpoint) (node_filesystem_avail_bytes{job=\"$job\",  instance=\"$instance\", fstype!=\"\", mountpoint!=\"\"})\n"
    }
   ]
  },
  {
   "title": "Disk Space Capacity",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " sum by (node) (node_filesystem_size_bytes{job=\"$job\",node=\"$kube_node\",device!~'rootfs'})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{job=\"$job\", instance=\"$instance\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\"}[$__rate_interval])",
     "legendFormat": "{{device}} read"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{job=\"$job\", instance=\"$instance\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\"}[$__rate_interval])",
     "legendFormat": "{{device}} written"
    },
    {
     "expr": "rate(node_disk_io_time_seconds_total{job=\"$job\", instance=\"$instance\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\"}[$__rate_interval])",
     "legendFormat": "{{device}} io time"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 } },
  {
   "title": "Current Network Received",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_bytes_total{job=\"kubernetes-service-endpoints\",node=\"$kube_node\"}[$__rate_interval]))*8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Network Transmitted",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(node_network_transmit_bytes_total{job=\"kubernetes-service-endpoints\",node=\"$kube_node\"}[$__rate_interval]))*8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of Received Packet Dropped",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_drop_total{node=\"$kube_node\", job=\"kubernetes-service-endpoints\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Storage IOPS (R+W)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (irate(node_disk_writes_completed_total{instance=\"$instance\",job=\"$job\",device=~\"$diskdevices\"}[$__rate_interval])+irate(node_disk_writes_completed_total{instance=\"$instance\",job=\"$job\",device=~\"$diskdevices\"}[$__rate_interval])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Received",
   "type": "graph",
   "description": "Network received (bits/s)",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 97 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"$job\", instance=\"$instance\", device!=\"lo\"}[$__rate_interval]) * 8",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Network Transmitted",
   "type": "graph",
   "description": "Network transmitted (bits/s)",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 97 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"$job\", instance=\"$instance\", device!=\"lo\"}[$__rate_interval]) * 8",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}