{
 "title": "Cluster Detail (Deprecated)",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(mo_cluster_info,main_cluster)"
    }
   },
   {
    "name": "unit",
    "query": {
     "query": "label_values(mo_cluster_info{cluster=\"$cluster\"},unit)"
    }
   },
   { "name": "ds_prom", "query": "prometheus" },
   { "name": "loki", "query": "loki" },
   {
    "name": "account",
    "label": "account",
    "query": {
     "query": "label_values(sql_statement_total{matrixone_cloud_main_cluster=\"$cluster\"},account)"
    }
   },
   {
    "name": "owner",
    "label": "owner",
    "query": {
     "query": "label_values(sql_statement_total{matrixone_cloud_main_cluster=\"$cluster\"},matrixorigin_io_owner)"
    }
   },
   {
    "name": "phase",
    "query": {
     "query": "label_values(up,pool_matrixorigin_io_phase)"
    }
   },
   {
    "name": "interval",
    "label": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "groupBy", "query": "__name__,__name__\\,pod" },
   {
    "name": "pod",
    "query": {
     "query": "label_values(up{matrixorigin_io_owner=~\"$owner\", pool_matrixorigin_io_phase=~\"$phase\"},pod)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(kube_pod_info{pod=~\"$pod|$syspod\"},node)"
    }
   },
   {
    "name": "syspod",
    "label": "syspod",
    "query": {
     "query": "label_values(up{namespace=\"$cluster\", matrixone_cloud_component!=\"cn\"},pod)"
    }
   },
   {
    "name": "hpa",
    "query": {
     "query": "label_values(kube_horizontalpodautoscaler_status_desired_replicas{horizontalpodautoscaler=~\"keda-hpa-$owner-.*\"},horizontalpodautoscaler)"
    }
   },
   {
    "name": "pvc",
    "query": {
     "query": "label_values(kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\"mo-data-$pod\"},persistentvolumeclaim)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "TPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(sql_transaction_total{account=~\"$account\", matrixone_cloud_main_cluster=~\"$cluster\", matrixorigin_io_owner=~\"$owner\"}[$interval])) by (account)",
     "legendFormat": "{{account}}"
    },
    {
     "expr": "sum(rate(sql_transaction_errors{account=~\"$account\", matrixone_cloud_main_cluster=~\"$cluster\", matrixorigin_io_owner=~\"$owner\"}[$interval])) by (account, pod)",
     "legendFormat": "{{account}}-{{pod}}-ERR"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "sum by(account, matrixorigin_io_owner, pod) (increase(sql_transaction_total{account=~\"$account\", matrixone_cloud_main_cluster=~\"$cluster\", matrixorigin_io_owner=~\"$owner\"}[$__range]))",
     "legendFormat": "{{account}}"
    }
   ]
  },
  {
   "title": "Statement Execute Percentile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, $groupBy) (rate(mo_txn_statement_duration_seconds_bucket{matrixone_cloud_main_cluster=~\"$cluster\", matrixorigin_io_owner=~\"$owner\", type=\"execute\", pod=~\"$pod\"}[$__rate_interval])))",
     "legendFormat": "P95-{{namespace}}{{pod}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, $groupBy) (rate(mo_txn_statement_duration_seconds_bucket{matrixone_cloud_main_cluster=~\"$cluster\", matrixorigin_io_owner=~\"$owner\", type=\"execute\", pod=~\"$pod\"}[$__rate_interval])))",
     "legendFormat": "P99-{{namespace}}{{pod}}"
    },
    {
     "expr": "histogram_quantile(0.999, sum by(le, $groupBy) (rate(mo_txn_statement_duration_seconds_bucket{matrixone_cloud_main_cluster=~\"$cluster\", matrixorigin_io_owner=~\"$owner\", type=\"execute\", pod=~\"$pod\"}[$__rate_interval])))",
     "legendFormat": "P999-{{namespace}}{{pod}}"
    }
   ]
  },
  {
   "title": "Txn Life Percentile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, $groupBy) (rate(mo_txn_life_duration_seconds_bucket{matrixone_cloud_main_cluster=~\"$cluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$__rate_interval])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le, $groupBy) (rate(mo_txn_life_duration_seconds_bucket{matrixone_cloud_main_cluster=~\"$cluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$__rate_interval])))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.999, sum by(le, $groupBy) (rate(mo_txn_life_duration_seconds_bucket{matrixone_cloud_main_cluster=~\"$cluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$__rate_interval])))",
     "legendFormat": "P999"
    }
   ]
  },
  {
   "title": "Txn Avg Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(mo_txn_life_duration_seconds_sum{matrixone_cloud_main_cluster=~\"$cluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by ($groupBy) / sum(rate(mo_txn_life_duration_seconds_count{matrixone_cloud_main_cluster=~\"$cluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by ($groupBy)",
     "legendFormat": "AVG-{{pod}}"
    },
    {
     "expr": "sum(mo_txn_queue_size{matrixone_cloud_main_cluster=~\"$cluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\", type!=\"active\"}) by (type)",
     "legendFormat": "QUEUE-{{type}}"
    }
   ]
  },
  {
   "title": "CPU (cores)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\"$pod\"}) by (pod)",
     "legendFormat": "{{account}}"
    }
   ]
  },
  {
   "title": "Memory (Working Set)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(node_namespace_pod_container:container_memory_working_set_bytes{pod=~\"$pod\", container=\"main\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "targets": [
    {
     "expr": "sum(server_connections{account=~\"$account\", matrixone_cloud_main_cluster=~\"$cluster\", matrixorigin_io_owner=~\"$owner\"}) by (account, $groupBy)",
     "legendFormat": "{{account}}-{{pod}}"
    }
   ]
  },
  {
   "title": "Receive Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{pod=~\"$pod\"}[$interval])) by (pod)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Transmit Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{pod=~\"$pod\"}[$interval])) by (pod)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Cache Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(\n  sum without(instance, node) (topk(1, (kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", persistentvolumeclaim=~\"$pvc\"})) by (persistentvolumeclaim))\n  -\n  sum without(instance, node) (topk(1, (kubelet_volume_stats_available_bytes{job=\"kubelet\", metrics_path=\"/metrics\", persistentvolumeclaim=~\"$pvc\"})) by (persistentvolumeclaim))\n)\n",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Crash Analysis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pod Restart",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 16, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "sum(increase(kube_pod_container_status_restarts_total{pod=~\"$pod|$syspod\"}[$interval])) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Terminated Reason",
     "type": "table",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 33 },
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_last_terminated_reason{pod=~\"$pod|$syspod\", job=\"kubernetes-service-endpoints\"}) by (namespace, reason, pod)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Pod Scaling",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 16, "x": 0, "y": 41 },
     "targets": [
      {
       "expr": "sum(kube_horizontalpodautoscaler_status_desired_replicas{job=\"kubernetes-service-endpoints\", namespace=\"$cluster\", horizontalpodautoscaler=~\"$hpa\"}) by (horizontalpodautoscaler)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Crash Log",
     "type": "logs",
     "gridPos": { "h": 14, "w": 8, "x": 16, "y": 41 },
     "targets": [
      {
       "expr": "{matrixone_cloud_main_cluster=~\"$cluster\", pod=~\"$pod|$syspod\"} |~ \"FATAL|panic:\""
      }
     ]
    },
    {
     "title": "Pod Phase",
     "type": "status-history",
     "gridPos": { "h": 15, "w": 16, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(sum(kube_pod_status_phase{pod=~\"$pod|$syspod\", job=\"kubernetes-service-endpoints\", phase=\"Failed\"}) by (pod) * 1) + (sum(kube_pod_status_phase{pod=~\"$pod|$syspod\", job=\"kubernetes-service-endpoints\", phase=\"Pending\"}) by (pod) * 2) + (sum(kube_pod_status_phase{pod=~\"$pod|$syspod\", job=\"kubernetes-service-endpoints\", phase=\"Running\"}) by (pod) * 3) + (sum(up{pod=~\"$pod|$syspod\"}) by (pod) * 10)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "LogService Free Space",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by(persistentvolumeclaim) (kubelet_volume_stats_available_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$cluster\", persistentvolumeclaim=~\".*-log-.*\"})",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Node Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Load 5",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node_load5{node=~\"$node\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Node to Pod",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
     "targets": [
      {
       "expr": "sum(kube_pod_info{node=~\"$node\", pod=~\"$pod|$syspod\"}) by (pod, namespace, node)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "IO Util",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(node_disk_io_time_seconds_total{job=\"kubernetes-service-endpoints\", node=~\"$node\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\"}[$__rate_interval])) by (node, device)",
       "legendFormat": "{{node}}-{{device}}"
      }
     ]
    },
    {
     "title": "Disk Avail Bytes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(node_filesystem_avail_bytes{node=~\"$node\", fstype!=\"\", mountpoint=\"/\"}) by (node, device)",
       "legendFormat": "{{node}}-{{device}}"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(\n  sum((1 - sum without (mode) (rate(node_cpu_seconds_total{job=\"kubernetes-service-endpoints\", mode=~\"idle|iowait|steal\", node=~\"$node\"}[$interval])))) by (node)\n/ count by (node) (node_cpu_seconds_total{job=\"kubernetes-service-endpoints\", mode=\"idle\", node=~\"$node\"})\n)\n",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(\n  node_memory_MemTotal_bytes{job=\"kubernetes-service-endpoints\", node=~\"$node\"}\n-\n  node_memory_MemFree_bytes{job=\"kubernetes-service-endpoints\", node=~\"$node\"}\n-\n  node_memory_Buffers_bytes{job=\"kubernetes-service-endpoints\", node=~\"$node\"}\n-\n  node_memory_Cached_bytes{job=\"kubernetes-service-endpoints\", node=~\"$node\"}\n) / node_memory_MemTotal_bytes{job=\"kubernetes-service-endpoints\", node=~\"$node\"}\n",
       "legendFormat": "{{node}}"
      }
     ]
    }
   ]
  }
 ]
}