{
 "title": "Cluster Detail V2",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(mo_cluster_info,main_cluster)"
    }
   },
   { "name": "exclude", "query": "sys, none" },
   {
    "name": "unit",
    "query": {
     "query": "label_values(mo_cluster_info{cluster=\"$cluster\"},unit)"
    }
   },
   { "name": "ds_prom", "query": "prometheus" },
   { "name": "loki", "query": "loki" },
   {
    "name": "account",
    "label": "account",
    "query": {
     "query": "label_values(sql_statement_total{matrixone_cloud_main_cluster=\"$cluster\", account!=\"$exclude\"},account)"
    }
   },
   {
    "name": "owner",
    "label": "owner",
    "query": {
     "query": "label_values(sql_statement_total{matrixone_cloud_main_cluster=~\"$cluster\", account=~\"$account\"},matrixorigin_io_owner)"
    }
   },
   { "name": "groupBy", "query": "__name__,__name__\\,pod" },
   {
    "name": "phase",
    "query": {
     "query": "label_values(up,pool_matrixorigin_io_phase)"
    }
   },
   {
    "name": "interval",
    "label": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(up{matrixorigin_io_owner=~\"$owner\", pool_matrixorigin_io_phase=~\"$phase\"},pod)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(kube_pod_info{pod=~\"$pod|$syspod\"},node)"
    }
   },
   {
    "name": "syspod",
    "label": "syspod",
    "query": {
     "query": "label_values(up{namespace=\"$cluster\", matrixone_cloud_component!=\"cn\"},pod)"
    }
   },
   {
    "name": "hpa",
    "query": {
     "query": "label_values(kube_horizontalpodautoscaler_status_desired_replicas{horizontalpodautoscaler=~\"keda-hpa-$owner-.*\"},horizontalpodautoscaler)"
    }
   },
   {
    "name": "pvc",
    "query": {
     "query": "label_values(kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\"mo-data-$pod\"},persistentvolumeclaim)"
    }
   },
   { "name": "ds_mo", "query": "mysql" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Tenant Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "TPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(sql_transaction_total{account=~\"$account\", matrixone_cloud_main_cluster=~\"$cluster\", matrixorigin_io_owner=~\"$owner\", account!=\"$exclude\"}[$interval])) by (account, $groupBy) > 0",
     "legendFormat": "{{account}}"
    },
    {
     "expr": "sum(rate(sql_transaction_errors{account=~\"$account\", matrixone_cloud_main_cluster=~\"$cluster\", matrixorigin_io_owner=~\"$owner\", account!=\"$exclude\"}[$interval])) by (account, $groupBy)> 0",
     "legendFormat": "{{account}}-{{pod}}-ERR"
    }
   ]
  },
  {
   "title": "Usage by Pod",
   "type": "table",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 1 },
   "targets": [
    {
     "expr": "sum by(account, matrixorigin_io_owner, pod) (increase(sql_transaction_total{account=~\"$account\", matrixone_cloud_main_cluster=~\"$cluster\", matrixorigin_io_owner=~\"$owner\", account!=\"$exclude\"}[$__range])) > 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(account, matrixorigin_io_owner, pod) (increase(sql_statement_cu{account=~\"$account\", matrixone_cloud_main_cluster=~\"$cluster\", matrixorigin_io_owner=~\"$owner\", account!=\"$exclude\"}[$__range])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Statement Duration Avg",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum(rate(sql_statement_duration_total{account=~\"$account\", matrixone_cloud_main_cluster=~\"$cluster\", matrixorigin_io_owner=~\"$owner\", account!=\"$exclude\"}[$interval])) by (account, $groupBy) / sum(rate(sql_statement_total{account=~\"$account\", matrixone_cloud_main_cluster=~\"$cluster\", matrixorigin_io_owner=~\"$owner\", account!=\"$exclude\"}[$interval])) by (account, $groupBy) > 0",
     "legendFormat": "{{account}}-{{pod}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "sum(server_connections{account=~\"$account\", matrixone_cloud_main_cluster=~\"$cluster\", matrixorigin_io_owner=~\"$owner\", account!=\"$exclude\"}) by (account, $groupBy) > 0",
     "legendFormat": "{{account}}-{{pod}}"
    }
   ]
  },
  {
   "title": "Storage Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "max(server_storage_usage{account=~\"$account\", matrixone_cloud_main_cluster=~\"$cluster\", matrixorigin_io_owner=~\"$owner\", account!=\"$exclude\"}) by(account)",
     "legendFormat": "{{account}}"
    }
   ]
  },
  {
   "title": "CN Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU (cores)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\"$pod\"}) by (pod)",
       "legendFormat": "{{account}}"
      }
     ]
    },
    {
     "title": "Memory (Working Set)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max(node_namespace_pod_container:container_memory_working_set_bytes{pod=~\"$pod\", container=\"main\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Memory (RSS)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max(container_memory_rss{pod=~\"$pod\", container=\"main\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Statement Percentile (use groupBy)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le, $groupBy) (rate(mo_txn_statement_duration_seconds_bucket{matrixone_cloud_main_cluster=~\"$cluster\", matrixorigin_io_owner=~\"$owner\", type=\"execute\", pod=~\"$pod\"}[$__rate_interval]))) > 0",
       "legendFormat": "P95-{{namespace}}{{pod}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum by(le, $groupBy) (rate(mo_txn_statement_duration_seconds_bucket{matrixone_cloud_main_cluster=~\"$cluster\", matrixorigin_io_owner=~\"$owner\", type=\"execute\", pod=~\"$pod\"}[$__rate_interval]))) > 0",
       "legendFormat": "P99-{{namespace}}{{pod}}"
      },
      {
       "expr": "histogram_quantile(0.999, sum by(le, $groupBy) (rate(mo_txn_statement_duration_seconds_bucket{matrixone_cloud_main_cluster=~\"$cluster\", matrixorigin_io_owner=~\"$owner\", type=\"execute\", pod=~\"$pod\"}[$__rate_interval])))",
       "legendFormat": "P999-{{namespace}}{{pod}}"
      }
     ]
    },
    {
     "title": "Txn Life Percentile (use groupBy)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le, $groupBy) (rate(mo_txn_life_duration_seconds_bucket{matrixone_cloud_main_cluster=~\"$cluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$__rate_interval])))",
       "legendFormat": "P95"
      },
      {
       "expr": "histogram_quantile(0.99, sum by(le, $groupBy) (rate(mo_txn_life_duration_seconds_bucket{matrixone_cloud_main_cluster=~\"$cluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$__rate_interval])))",
       "legendFormat": "P99"
      },
      {
       "expr": "histogram_quantile(0.999, sum by(le, $groupBy) (rate(mo_txn_life_duration_seconds_bucket{matrixone_cloud_main_cluster=~\"$cluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$__rate_interval])))",
       "legendFormat": "P999"
      }
     ]
    },
    {
     "title": "Txn Avg Duration (use groupBy)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(mo_txn_life_duration_seconds_sum{matrixone_cloud_main_cluster=~\"$cluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by ($groupBy) / sum(rate(mo_txn_life_duration_seconds_count{matrixone_cloud_main_cluster=~\"$cluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\"}[$interval])) by ($groupBy)",
       "legendFormat": "AVG-{{pod}}"
      },
      {
       "expr": "sum(mo_txn_queue_size{matrixone_cloud_main_cluster=~\"$cluster\", matrixorigin_io_owner=~\"$owner\", pod=~\"$pod\", type!=\"active\"}) by (type, $groupBy)",
       "legendFormat": "QUEUE-{{type}}-{{pod}}"
      }
     ]
    },
    {
     "title": "Receive Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_bytes_total{pod=~\"$pod\"}[$interval])) by (pod)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Transmit Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(irate(container_network_transmit_bytes_total{pod=~\"$pod\"}[$interval])) by (pod)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Cache Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(\n  sum without(instance, node) (topk(1, (kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", persistentvolumeclaim=~\"$pvc\"})) by (persistentvolumeclaim))\n  -\n  sum without(instance, node) (topk(1, (kubelet_volume_stats_available_bytes{job=\"kubelet\", metrics_path=\"/metrics\", persistentvolumeclaim=~\"$pvc\"})) by (persistentvolumeclaim))\n)\n",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pod Mapping (Node, UUID, IP)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pod Mapping",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "sum(present_over_time(up{pod=~\"$pod\", matrixone_cloud_cn_uuid!=\"\"}[$__range])) by (pod, matrixone_cloud_cn_uuid, matrixorigin_io_owner)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(present_over_time(kube_pod_info{pod=~\"$pod|$syspod\", pod_ip!=\"\"}[$__range])) by (pod, namespace, node, pod_ip)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Proxy and Session",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "New Connection per Sec",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(mo_proxy_connect_counter{pod=~\"$syspod\", pod=~\".*proxy.*\"}[$interval])) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Connections",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(server_connections{pod=~\"($syspod|$pod)\"}) ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Proxy CPU",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 13 },
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\"$syspod\", pod=~\".*proxy.*\"}) by (pod)",
       "legendFormat": "{{account}}"
      }
     ]
    },
    {
     "title": "Processlist",
     "type": "table",
     "gridPos": { "h": 14, "w": 6, "x": 18, "y": 13 },
     "targets": [
      {
       "dataset": "system_metrics",
       "rawSql": "SELECT SUBSTRING_INDEX(SUBSTRING_INDEX(proxy_host, ':', 1), ':', -1) as proxy, host as cn, count(*) FROM processlist() as a GROUP BY proxy, cn;"
      }
     ]
    },
    {
     "title": "Connection Transfers",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(increase(mo_proxy_connection_transfer_counter{pod=~\"$syspod\", pod=~\".*proxy.*\"}[$interval])) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Proxy Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{pod=~\"$syspod\", pod=~\".*proxy.*\"}[$interval])) by (pod)",
       "legendFormat": "{{pod}}-in"
      },
      {
       "expr": "-sum(rate(container_network_transmit_bytes_total{pod=~\"$syspod\", pod=~\".*proxy.*\"}[$interval])) by (pod)",
       "legendFormat": "{{pod}}-out"
      }
     ]
    },
    {
     "title": "Proxy Memory (Working Set)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max(node_namespace_pod_container:container_memory_working_set_bytes{pod=~\"$syspod\", pod=~\".*proxy.*\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "TN, Log",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "TN CPU",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\"$syspod\", pod=~\".*dn.*\"}) by (pod)",
       "legendFormat": "{{account}}"
      }
     ]
    },
    {
     "title": "TN Memory (Working Set)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max(node_namespace_pod_container:container_memory_working_set_bytes{pod=~\"$syspod\", container=\"main\", pod=~\".*dn.*\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "TN Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{pod=~\"$syspod\", pod=~\".*dn.*\"}[$interval])) by (pod)",
       "legendFormat": "{{pod}}-in"
      },
      {
       "expr": "-sum(rate(container_network_transmit_bytes_total{pod=~\"$syspod\", pod=~\".*dn.*\"}[$interval])) by (pod)",
       "legendFormat": "{{pod}}-out"
      }
     ]
    },
    {
     "title": "TN Commit",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 21 },
     "targets": [
      {
       "expr": "sum(rate(mo_txn_commit_total{type!=\"cn\",matrixone_cloud_main_cluster=~\"$cluster\", pod=~\"$syspod\", pod=~\".*dn.*\"}[$interval])) by (pod, type)",
       "legendFormat": "{{pod}}-{{type}}"
      }
     ]
    },
    {
     "title": "Log CPU",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\"$syspod\", pod=~\".*log.*\"}) by (pod)",
       "legendFormat": "{{account}}"
      }
     ]
    },
    {
     "title": "Log Memory (Working Set)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max(node_namespace_pod_container:container_memory_working_set_bytes{pod=~\"$syspod\", container=\"main\", pod=~\".*log.*\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Log Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{pod=~\"$syspod\", pod=~\".*log.*\"}[$interval])) by (pod)",
       "legendFormat": "{{pod}}-in"
      },
      {
       "expr": "-sum(rate(container_network_transmit_bytes_total{pod=~\"$syspod\", pod=~\".*log.*\"}[$interval])) by (pod)",
       "legendFormat": "{{pod}}-out"
      }
     ]
    },
    {
     "title": "LogService Free Space",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by(persistentvolumeclaim) (kubelet_volume_stats_available_bytes{job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$cluster\", persistentvolumeclaim=~\".*-log-.*\"})",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Scaling and Crash",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pod Image and Liveness",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "sum(kube_pod_container_info{pod=~\"($pod|$syspod)\"}) by (matrixorigin_io_owner, pod, image)",
       "legendFormat": "{{matrixorigin_io_owner}}/{{pod}}: {{image}}"
      }
     ]
    },
    {
     "title": "Scaling History",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
     "targets": [
      {
       "expr": "sum(kube_horizontalpodautoscaler_status_desired_replicas{job=\"kubernetes-service-endpoints\", namespace=\"$cluster\", horizontalpodautoscaler=~\"($hpa|.*default.*)\"}) by (horizontalpodautoscaler)",
       "legendFormat": "{{horizontalpodautoscaler}}-replicas"
      }
     ]
    },
    {
     "title": "Scaling Metrics",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(kube_horizontalpodautoscaler_status_target_metric{job=\"kubernetes-service-endpoints\", namespace=\"$cluster\", horizontalpodautoscaler=~\"($hpa|.*default.*)\", metric_name=\"cpu\"}) by (horizontalpodautoscaler)",
       "legendFormat": "{{horizontalpodautoscaler}}-current"
      },
      {
       "expr": "max(sum(kube_horizontalpodautoscaler_spec_target_metric{job=\"kubernetes-service-endpoints\", namespace=\"$cluster\", horizontalpodautoscaler=~\"($hpa|.*default.*)\", metric_name=\"cpu\"}) by (horizontalpodautoscaler))",
       "legendFormat": "Target CPU"
      }
     ]
    },
    {
     "title": "Pod Restart",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "sum(increase(kube_pod_container_status_restarts_total{pod=~\"($pod|$syspod)\"}[$interval])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Terminated Reason",
     "type": "table",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_last_terminated_reason{pod=~\"$pod|$syspod\", job=\"kubernetes-service-endpoints\"}) by (namespace, reason, pod)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Crash and Restart Log",
     "type": "logs",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
     "targets": [
      {
       "expr": "{matrixone_cloud_main_cluster=~\"$cluster\", pod=~\"$pod|$syspod\"} |~ \"(FATAL|panic:|mo-service -cfg)\" | keep pod"
      }
     ]
    },
    {
     "title": "Pod Phase",
     "type": "status-history",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(sum(kube_pod_status_phase{pod=~\"$pod|$syspod\", job=\"kubernetes-service-endpoints\", phase=\"Failed\"}) by (pod) * 1) + (sum(kube_pod_status_phase{pod=~\"$pod|$syspod\", job=\"kubernetes-service-endpoints\", phase=\"Pending\"}) by (pod) * 2) + (sum(kube_pod_status_phase{pod=~\"$pod|$syspod\", job=\"kubernetes-service-endpoints\", phase=\"Running\"}) by (pod) * 3) + (sum(up{pod=~\"$pod|$syspod\"}) by (pod) * 10)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Node Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "IO Util",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(node_disk_io_time_seconds_total{job=\"kubernetes-service-endpoints\", node=~\"$node\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\"}[$__rate_interval])) by (node, device)",
       "legendFormat": "{{node}}-{{device}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(\n  node_memory_MemTotal_bytes{job=\"kubernetes-service-endpoints\", node=~\"$node\"}\n-\n  node_memory_MemFree_bytes{job=\"kubernetes-service-endpoints\", node=~\"$node\"}\n-\n  node_memory_Buffers_bytes{job=\"kubernetes-service-endpoints\", node=~\"$node\"}\n-\n  node_memory_Cached_bytes{job=\"kubernetes-service-endpoints\", node=~\"$node\"}\n) / node_memory_MemTotal_bytes{job=\"kubernetes-service-endpoints\", node=~\"$node\"}\n",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Disk Avail Bytes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(node_filesystem_avail_bytes{node=~\"$node\", fstype!=\"\", mountpoint=\"/\"}) by (node, device)",
       "legendFormat": "{{node}}-{{device}}"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(\n  sum((1 - sum without (mode) (rate(node_cpu_seconds_total{job=\"kubernetes-service-endpoints\", mode=~\"idle|iowait|steal\", node=~\"$node\"}[$interval])))) by (node)\n/ count by (node) (node_cpu_seconds_total{job=\"kubernetes-service-endpoints\", mode=\"idle\", node=~\"$node\"})\n)\n",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Load 5",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node_load5{node=~\"$node\"}",
       "legendFormat": "{{node}}"
      }
     ]
    }
   ]
  }
 ]
}