{
 "title": "MO / ETLMerge",
 "tags": [
  "MO",
  "moob"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance_id",
    "query": {
     "query": "label_values(controlplane_instance_detail_info,id)"
    }
   },
   {
    "name": "unit",
    "query": {
     "query": "label_values(controlplane_instance_detail_info{id=\"$instance_id\"},unit)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(up,matrixone_cloud_main_cluster)"
    }
   },
   { "name": "ds_prom", "query": "prometheus" },
   { "name": "ds_loki", "query": "loki" },
   { "name": "ds_mysql", "query": "mysql" }
  ]
 },
 "panels": [
  { "title": "Base Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Instance Info",
   "type": "table",
   "description": "MOCloud",
   "gridPos": { "h": 4, "w": 19, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "controlplane_instance_detail_info{id=\"$instance_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MO Account Info",
   "type": "table",
   "description": "MO Cluster",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "targets": [
    {
     "dataset": "a",
     "rawSql": "select REPLACE(\"$instance_id\", '-', '_') as account_id"
    }
   ]
  },
  {
   "title": "Log",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "ETLMerge upload files",
     "type": "logs",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "{matrixone_cloud_main_cluster=\"$cluster\", matrixorigin_io_component=\"CNSet\"} |= `upload files success`"
      }
     ]
    },
    {
     "title": "ETLMerge run log",
     "type": "logs",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "{matrixone_cloud_main_cluster=\"$cluster\", matrixorigin_io_component=\"CNSet\"} |= `ETLMerge`"
      }
     ]
    }
   ]
  }
 ]
}