{
 "title": "MO / MOLogger",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "unit",
    "query": {
     "query": "label_values(controlplane_instance_detail_info,unit)"
    }
   },
   { "name": "datasouce", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(up,matrixone_cloud_main_cluster)"
    }
   },
   { "name": "loki", "query": "loki" },
   { "name": "mo", "query": "mysql" },
   { "name": "limit", "query": "100, 1000, 3000" },
   {
    "name": "instance_id",
    "query": "select account_name from mo_catalog.mo_account;"
   }
  ]
 },
 "panels": [
  { "title": "Connection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "mo_logger connection",
   "type": "table",
   "gridPos": { "h": 18, "w": 9, "x": 0, "y": 1 },
   "targets": [
    {
     "dataset": "a",
     "rawSql": "select client_host, host mo_host, node_id mo_node from processlist() p where p.user = 'mo_logger' order by mo_host, node_id;"
    }
   ]
  },
  {
   "title": "mo_logger connection",
   "type": "table",
   "gridPos": { "h": 18, "w": 4, "x": 9, "y": 1 },
   "targets": [
    {
     "dataset": "a",
     "rawSql": "select host mo_host, count(1) from processlist() p where p.user = 'mo_logger' group by mo_host order by mo_host;"
    }
   ]
  },
  {
   "title": "Up (有误差，idel 的owner 不会修改）",
   "type": "table",
   "gridPos": { "h": 16, "w": 11, "x": 13, "y": 1 },
   "targets": [
    {
     "expr": "count by(instance, matrixone_cloud_cn_uuid, matrixorigin_io_owner, matrixorigin_io_component) (up{matrixone_cloud_main_cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "proxy info",
   "type": "table",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 17 },
   "targets": [
    {
     "expr": "count by (pod_ip, pod) (kube_pod_info{namespace=\"$cluster\", pod=~\".+proxy.+\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backend Servers",
   "type": "table",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 19 },
   "targets": [
    { "rawSql": "show backend servers;" }
   ]
  },
  {
   "title": "Log Analysis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "MetricStorage log",
     "type": "logs",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "{matrixone_cloud_main_cluster=~\"$cluster\", matrixorigin_io_component=\"CNSet\"} |= `MetricStorage`"
      }
     ]
    },
    {
     "title": "task_service CN",
     "type": "logs",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "{matrixone_cloud_main_cluster=~\"$cluster\", matrixorigin_io_component=\"CNSet\"} |~ `server_task.go|server_task.go|task_service_cron.go|runner-id`"
      }
     ]
    },
    {
     "title": "task_service LOG",
     "type": "logs",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 40 },
     "targets": [
      {
       "expr": "{matrixone_cloud_main_cluster=~\"$cluster\", matrixorigin_io_component=\"LogSet\"} |~ `task_service|task_scheduler.go|task_service_cron.go`"
      }
     ]
    }
   ]
  },
  {
   "title": "MO DB data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "storage_storage_usage (last records)",
     "type": "table",
     "gridPos": { "h": 11, "w": 19, "x": 0, "y": 19 },
     "targets": [
      {
       "dataset": "a",
       "rawSql": "select * from system_metrics.server_storage_usage where $__timeFilter(collecttime) and ($instance_id=\"ALL\" OR account = replace($instance_id, '-', '_')) order by collecttime desc limit $limit; "
      }
     ]
    },
    {
     "title": "storage_storage_usage count(account)",
     "type": "table",
     "gridPos": { "h": 11, "w": 5, "x": 19, "y": 19 },
     "targets": [
      {
       "dataset": "a",
       "rawSql": "select collecttime, count(*) account_cnt from system_metrics.server_storage_usage where collecttime between date_sub($__timeTo(), interval 1 minute) and $__timeTo() and ($instance_id=\"ALL\" OR account = replace($instance_id, '-', '_')) group by collecttime order by collecttime desc limit $limit; "
      }
     ]
    },
    {
     "title": "storage_storage_usage (last records)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "MiBs" } },
     "targets": [
      {
       "dataset": "a",
       "rawSql": "select * from system_metrics.server_storage_usage where $__timeFilter(collecttime) and ($instance_id=\"ALL\" OR account = replace($instance_id, '-', '_')) order by collecttime desc limit $limit; "
      }
     ]
    }
   ]
  },
  {
   "title": "MO task_service status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Last Task",
     "type": "table",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 16 },
     "targets": [
      {
       "dataset": "a",
       "rawSql": "select task_id taskID, task_metadata_id taskMetadataID, task_runner node_uuid, FROM_UNIXTIME(create_at/1e3) as create_time, FROM_UNIXTIME(end_at/1e3) as end_time, IF(task_status=0, 'NOT Start', IF(task_status=1, \"Running\", IF(task_status=2, \"Failed\", \"Unknown\"))) taskStatus, * from mo_task.sys_async_task\nwhere task_metadata_id like 'Storage%' order by create_at desc limit 1;"
      }
     ]
    },
    {
     "title": "All Backend Servers",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 20 },
     "targets": [
      { "dataset": "a", "rawSql": "show backend servers;" }
     ]
    },
    {
     "title": "mo_task exec history (limit $limit)",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 31 },
     "targets": [
      {
       "dataset": "a",
       "rawSql": "select * from system.statement_info where $__timeFilter(request_at) and user in (select user from system.statement_info where $__timeFilter(request_at) and `database` = 'mo_task' order by request_at desc limit 1) order by request_at desc limit $limit;"
      }
     ]
    },
    {
     "title": "mo_task exec history - last 10 failed",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 42 },
     "targets": [
      {
       "dataset": "a",
       "rawSql": "select * from system.statement_info where $__timeFilter(request_at) and user in (select user from system.statement_info where $__timeFilter(request_at) and `database` = 'mo_task' order by request_at desc limit 1) and status = 'Failed' order by request_at desc limit 10;"
      }
     ]
    },
    {
     "title": "Backend Servers",
     "type": "table",
     "gridPos": { "h": 12, "w": 11, "x": 0, "y": 53 },
     "targets": [
      { "dataset": "a", "rawSql": "show backend servers;" }
     ]
    }
   ]
  }
 ]
}