{
 "title": "MO / Query History",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "unit",
    "query": {
     "query": "label_values(controlplane_instance_detail_info,unit)"
    }
   },
   { "name": "datasouce", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(up,matrixone_cloud_main_cluster)"
    }
   },
   { "name": "loki", "query": "loki" },
   { "name": "mo", "query": "mysql" },
   {
    "name": "account",
    "query": "select account_name from mo_catalog.mo_account;"
   },
   { "name": "status", "query": "Failed, Success" },
   {
    "name": "sql_source_type",
    "label": "sql_source",
    "query": "external_sql,cloud_user_sql,cloud_nonuser_sql,internal_sql"
   },
   { "name": "query_type", "query": "DQL, DDL, DML, DCL, TCL, Other" },
   {
    "name": "order_condition",
    "label": "order",
    "query": "request_at DESC, cu DESC, duration DESC"
   },
   { "name": "limit", "query": "20, 50, 100, 1000, 3000" },
   { "name": "session_id" },
   { "name": "statement_id" },
   { "name": "node_uuid" },
   { "name": "filter_condition", "query": "1" }
  ]
 },
 "panels": [
  { "title": "Default", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "query history",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "dataset": "a",
     "rawSql": "SELECT * FROM\n    (SELECT /*old_version_see_0416*/ json_extract(stats,\"$[8]\") AS `cu`,\n         `statement`, statement_id, `duration`, `duration`/1e9 sec, `status` , `query_type` , `request_at` , system.statement_info.response_at,\n         `account`, `user` , `database` , `transaction_id` , `session_id` , `rows_read` , `bytes_scan` , `result_count`, `aggr_count`,\n         `sql_source_type`, `err_code`, `error`, `node_uuid`, `stats`\n    FROM system.statement_info\n    WHERE $__timeFilter(request_at)\n            AND system.statement_info.account = \"$account\"\n            AND (\"$sql_source_type\" = \"'ALL'\" OR sql_source_type IN ($sql_source_type))\n            AND ($status = \"ALL\" OR status = $status)\n            AND (\"$node_uuid\" = \"\" OR node_uuid = \"$node_uuid\")\n            AND (\"$session_id\" = \"\" OR session_id = \"$session_id\")\n            AND (\"$statement_id\" = \"\" OR statement_id = \"$statement_id\")\n            AND ($filter_condition)\n            AND ($query_type=\"ALL\" OR query_type = $query_type)) t\nORDER BY  $order_condition LIMIT $limit;"
    }
   ]
  },
  {
   "title": "connection status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "show processlist",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
     "targets": [
      {
       "dataset": "db1",
       "rawSql": "select * from processlist() p where p.account = \"$account\";"
      }
     ]
    },
    {
     "title": "server_connections (from prometheus)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "server_connections{account=\"$account\"}",
       "legendFormat": "{{instance}} - {{pod}}"
      }
     ]
    },
    {
     "title": "server_connections (from DB)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "dataset": "db1",
       "rawSql": "select FROM_UNIXTIME(UNIX_TIMESTAMP(concat(left(collecttime, 16), \":59\"))) as collecttime, sum(value)/4 as value from system_metrics.server_connections where account = \"$account\" and $__timeFilter(collecttime) group by left(collecttime, 16);"
      }
     ]
    }
   ]
  },
  {
   "title": "Query ExecPlan",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "query history (with exec_plan)",
     "type": "table",
     "description": "must filter by statement_id",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
     "targets": [
      {
       "dataset": "a",
       "rawSql": "SELECT * FROM\n    (SELECT /*old_version_see_0416*/ json_extract(stats,\"$[8]\") AS `cu`,\n         `statement`, statement_id, `duration`, `duration`/1e9 sec, `status` , `query_type` , `request_at` , system.statement_info.response_at,\n         `account`, `user` , `database` , `transaction_id` , `session_id` , `exec_plan`\n    FROM system.statement_info\n    WHERE $__timeFilter(request_at)\n            AND (\"$statement_id\" != \"\" AND statement_id = \"$statement_id\")\n            AND system.statement_info.account = \"$account\"\n            AND (\"$sql_source_type\" = \"'ALL'\" OR sql_source_type IN ($sql_source_type))\n            AND ($status = \"ALL\" OR status = $status)\n            AND (\"$node_uuid\" = \"\" OR node_uuid = \"$node_uuid\")\n            AND (\"$session_id\" = \"\" OR session_id = \"$session_id\")\n            AND ($query_type=\"ALL\" OR query_type = $query_type)) t\nORDER BY  $order_condition LIMIT $limit;"
      }
     ]
    }
   ]
  },
  {
   "title": "Backend Servers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "show backend servers",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
     "targets": [
      { "dataset": "db1", "rawSql": "show backend servers;" }
     ]
    }
   ]
  },
  {
   "title": "MO task_service status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Last Task",
     "type": "table",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 31 },
     "targets": [
      {
       "dataset": "a",
       "rawSql": "select task_id taskID, task_metadata_id taskMetadataID, task_runner node_uuid, FROM_UNIXTIME(create_at/1e3) as create_time, FROM_UNIXTIME(end_at/1e3) as end_time, IF(task_status=0, 'NOT Start', IF(task_status=1, \"Running\", IF(task_status=2, \"Failed\", \"Unknown\"))) taskStatus, * from mo_task.sys_async_task\nwhere task_metadata_id like 'Storage%' order by create_at desc limit 1;"
      }
     ]
    },
    {
     "title": "All Backend Servers",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 35 },
     "targets": [
      { "dataset": "a", "rawSql": "show backend servers;" }
     ]
    },
    {
     "title": "mo_task exec history (limit $limit)",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 46 },
     "targets": [
      {
       "dataset": "a",
       "rawSql": "select * from system.statement_info where $__timeFilter(request_at) and user in (select user from system.statement_info where $__timeFilter(request_at) and `database` = 'mo_task' order by request_at desc limit 1) order by request_at desc limit $limit;"
      }
     ]
    },
    {
     "title": "mo_task exec history - last 10 failed",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 57 },
     "targets": [
      {
       "dataset": "a",
       "rawSql": "select * from system.statement_info where $__timeFilter(request_at) and user in (select user from system.statement_info where $__timeFilter(request_at) and `database` = 'mo_task' order by request_at desc limit 1) and status = 'Failed' order by request_at desc limit 10;"
      }
     ]
    }
   ]
  }
 ]
}