{
 "title": "MO / StorageUsage",
 "tags": [
  "alert",
  "moob"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "unit",
    "query": {
     "query": "label_values(controlplane_instance_detail_info,unit)"
    }
   },
   { "name": "datasouce", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(up,matrixone_cloud_main_cluster)"
    }
   },
   { "name": "loki", "query": "loki" },
   { "name": "mo", "query": "mysql" },
   { "name": "limit", "query": "100, 1000, 3000" },
   {
    "name": "instance_id",
    "query": "select account_name from mo_catalog.mo_account;"
   }
  ]
 },
 "panels": [
  { "title": "Main - Metric", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Alert Value",
   "type": "status-history",
   "description": "Exist means act alert",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "group by (matrixone_cloud_main_cluster) (up{matrixone_cloud_main_cluster=~\"$cluster\", matrixone_cloud_component=\"cn\"}) * 1 unless group by (matrixone_cloud_main_cluster) (server_storage_usage{matrixone_cloud_main_cluster=~\"$cluster\", matrixone_cloud_component=\"cn\"}) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "absent (details)",
   "type": "table",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 1 },
   "targets": [
    {
     "expr": "group by (matrixone_cloud_main_cluster) (up{matrixone_cloud_main_cluster=~\"$cluster\"}) * 0 unless group by (matrixone_cloud_main_cluster) (server_storage_usage{matrixone_cloud_main_cluster=~\"$cluster\"}) >= 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "storage_storage_usage (metric count)",
   "type": "timeseries",
   "description": "number of diff accounts",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "count by (matrixone_cloud_main_cluster,job) (server_storage_usage{matrixone_cloud_main_cluster=~\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "up",
   "type": "timeseries",
   "description": "number of diff pods",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "count by (matrixone_cloud_main_cluster,job) (up{matrixone_cloud_main_cluster=~\"$cluster\"})",
     "legendFormat": "up - {{matrixone_cloud_main_cluster}} - {{job}}"
    }
   ]
  },
  {
   "title": "Log Analysis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "MetricStorage log",
     "type": "logs",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "{matrixone_cloud_main_cluster=~\"$cluster\", matrixorigin_io_component=\"CNSet\"} |= `MetricStorage`"
      }
     ]
    },
    {
     "title": "task_service CN",
     "type": "logs",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "{matrixone_cloud_main_cluster=~\"$cluster\", matrixorigin_io_component=\"CNSet\"} |~ `server_task.go|server_task.go|task_service_cron.go|runner-id`"
      }
     ]
    },
    {
     "title": "task_service LOG",
     "type": "logs",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 47 },
     "targets": [
      {
       "expr": "{matrixone_cloud_main_cluster=~\"$cluster\", matrixorigin_io_component=\"LogSet\"} |~ `task_service|task_scheduler.go|task_service_cron.go`"
      }
     ]
    }
   ]
  },
  {
   "title": "MO DB data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "storage_storage_usage (last records)",
     "type": "table",
     "gridPos": { "h": 11, "w": 19, "x": 0, "y": 3 },
     "targets": [
      {
       "dataset": "a",
       "rawSql": "select * from system_metrics.server_storage_usage where $__timeFilter(collecttime) and ($instance_id=\"ALL\" OR account = replace($instance_id, '-', '_')) order by collecttime desc limit $limit; "
      }
     ]
    },
    {
     "title": "storage_storage_usage count(account)",
     "type": "table",
     "gridPos": { "h": 11, "w": 5, "x": 19, "y": 3 },
     "targets": [
      {
       "dataset": "a",
       "rawSql": "select collecttime, count(*) account_cnt from system_metrics.server_storage_usage where collecttime between date_sub($__timeTo(), interval 1 minute) and $__timeTo() and ($instance_id=\"ALL\" OR account = replace($instance_id, '-', '_')) group by collecttime order by collecttime desc limit $limit; "
      }
     ]
    },
    {
     "title": "storage_storage_usage (last records)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "MiBs" } },
     "targets": [
      {
       "dataset": "a",
       "rawSql": "select * from system_metrics.server_storage_usage where $__timeFilter(collecttime) and ($instance_id=\"ALL\" OR account = replace($instance_id, '-', '_')) order by collecttime desc limit $limit; "
      }
     ]
    }
   ]
  },
  {
   "title": "MO task_service status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Last Task",
     "type": "table",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 27 },
     "targets": [
      {
       "dataset": "a",
       "rawSql": "select task_id taskID, task_metadata_id taskMetadataID, task_runner node_uuid, FROM_UNIXTIME(create_at/1e3) as create_time, FROM_UNIXTIME(end_at/1e3) as end_time, IF(task_status=0, 'NOT Start', IF(task_status=1, \"Running\", IF(task_status=2, \"Failed\", \"Unknown\"))) taskStatus, * from mo_task.sys_async_task\nwhere task_metadata_id like 'Storage%' order by create_at desc limit 1;"
      }
     ]
    },
    {
     "title": "All Backend Servers",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 31 },
     "targets": [
      { "dataset": "a", "rawSql": "show backend servers;" }
     ]
    },
    {
     "title": "mo_task exec history (limit $limit)",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 42 },
     "targets": [
      {
       "dataset": "a",
       "rawSql": "select * from system.statement_info where $__timeFilter(request_at) and user in (select user from system.statement_info where $__timeFilter(request_at) and `database` = 'mo_task' order by request_at desc limit 1) order by request_at desc limit $limit;"
      }
     ]
    },
    {
     "title": "mo_task exec history - last 10 failed",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 53 },
     "targets": [
      {
       "dataset": "a",
       "rawSql": "select * from system.statement_info where $__timeFilter(request_at) and user in (select user from system.statement_info where $__timeFilter(request_at) and `database` = 'mo_task' order by request_at desc limit 1) and status = 'Failed' order by request_at desc limit 10;"
      }
     ]
    }
   ]
  }
 ]
}