{
 "title": "MOC Upgrade",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(mo_cluster_info,main_cluster)"
    }
   },
   {
    "name": "unit",
    "query": {
     "query": "label_values(mo_cluster_info{cluster=\"$cluster\"},unit)"
    }
   },
   { "name": "ds_prom", "query": "prometheus" },
   { "name": "loki", "query": "loki" },
   {
    "name": "interval",
    "label": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "ds_mo", "query": "mysql" },
   { "name": "central", "query": "prometheus" },
   {
    "name": "pod",
    "query": {
     "query": "label_values(up{matrixone_cloud_main_cluster=\"$cluster\"},pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Control Plane", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Images",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_info{namespace=~\"(cos|mo-cloud)\"}) by (pod, image)",
     "legendFormat": "{{pod}}: {{image}}"
    }
   ]
  },
  {
   "title": "Images",
   "type": "table",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 1 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_info{namespace=~\"(cos|mo-cloud)\"}) by (pod, image)",
     "legendFormat": "{{pod}}: {{image}}"
    }
   ]
  },
  {
   "title": "Error log",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum(rate({namespace=~\"(cos|mo-cloud)\"} |= `ERR`[$interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Restart",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 11 },
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{namespace=~\"(cos|mo-cloud)\"}[$interval])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster UP Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
   "targets": [
    { "expr": "sum(mo_cluster_up) by (unit)", "legendFormat": "{{unit}}" }
   ]
  },
  { "title": "$unit-$cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 }, "repeat": "cluster" },
  {
   "title": "MO Version",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_info{pod=~\"$pod\"}) by (image)",
     "legendFormat": "{{pod}}: {{image}}"
    }
   ]
  },
  {
   "title": "MO Pod Age",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - kube_pod_container_state_started{pod=~\"$pod\"} > 0",
     "legendFormat": "{{pod}}: {{image}}"
    }
   ]
  },
  {
   "title": "MO Pod Restart",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{pod=~\"$pod\"}[$interval])) by (pod)",
     "legendFormat": "{{pod}}: {{image}}"
    }
   ]
  },
  {
   "title": "SQL Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(sql_transaction_errors{matrixone_cloud_main_cluster=~\"$cluster\"}[$interval])) by (account)> 0",
     "legendFormat": "{{account}}-{{pod}}-ERR"
    }
   ]
  },
  {
   "title": "Statement Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum(rate(sql_statement_duration_total{matrixone_cloud_main_cluster=~\"$cluster\"}[$interval])) by (account) / sum(rate(sql_statement_total{matrixone_cloud_main_cluster=~\"$cluster\"}[$interval])) by (account) > 0",
     "legendFormat": "{{account}}-{{pod}}"
    }
   ]
  },
  {
   "title": "Sys Versions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_info{namespace=~\"(cos-system|mo-cloud|mo-system)\"}) by (pod, image)",
     "legendFormat": "{{pod}}: {{image}}"
    },
    {
     "expr": "sum(kube_pod_container_info{namespace=~\"$cluster\", pod=~\"local-service-.*\"}) by (pod, image)",
     "legendFormat": "{{pod}}: {{image}}"
    }
   ]
  },
  {
   "title": "Pod Phase",
   "type": "status-history",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(sum(kube_pod_status_phase{pod=~\"$pod\", job=\"kubernetes-service-endpoints\", phase=\"Failed\"}) by (pod) * 1) + (sum(kube_pod_status_phase{pod=~\"$pod\", job=\"kubernetes-service-endpoints\", phase=\"Pending\"}) by (pod) * 2) + (sum(kube_pod_status_phase{pod=~\"$pod\", job=\"kubernetes-service-endpoints\", phase=\"Running\"}) by (pod) * 3) + (sum(up{pod=~\"$pod\"}) by (pod) * 10)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Images",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_info{pod=~\"$pod\"}) by (namespace, pod, image)",
     "legendFormat": "{{pod}}: {{image}}"
    },
    {
     "expr": "sum(kube_pod_container_info{namespace=~\"(mo-ob|cos-system|mo-system|mo-cloud|cos|$cluster)\"}) by (namespace, pod, image)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}