{
 "title": "UnitAgent",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster_name",
    "query": {
     "query": "label_values(unit_agent_cluster_phase,cluster_name)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_status_ready,namespace)"
    }
   },
   {
    "name": "podName",
    "label": "podName",
    "query": {
     "query": "label_values(kube_pod_status_ready,pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster Phase",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(sum(unit_agent_cluster_phase{cluster_name=~\"$cluster_name\",phase=\"Creating\"}) by (cluster_name) * 1) + (sum(unit_agent_cluster_phase{cluster_name=~\"$cluster_name\",phase=\"Active\"}) by (cluster_name) * 2) + (sum(unit_agent_cluster_phase{cluster_name=~\"$cluster_name\",phase=\"Upgrading\"}) by (cluster_name) * 3) + (sum(unit_agent_cluster_phase{cluster_name=~\"$cluster_name\",phase=\"Suspended\"}) by (cluster_name) * 4) + (sum(unit_agent_cluster_phase{cluster_name=~\"$cluster_name\",phase=\"Hibernated\"}) by (cluster_name) * 5) + (sum(unit_agent_cluster_phase{cluster_name=~\"$cluster_name\",phase=\"Deleting\"}) by (cluster_name) * 6) + (sum(unit_agent_cluster_phase{cluster_name=~\"$cluster_name\",phase=\"Restricted\"}) by (cluster_name) * 7)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Ready Condition",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(sum(kube_pod_status_ready{namespace=~\"$namespace\",pod=~\"$podName\",job=\"kube-state-metrics\", condition=\"unknown\"}) by (pod) * 1) + (sum(kube_pod_status_ready{namespace=~\"$namespace\", pod=~\"$podName\",job=\"kube-state-metrics\", condition=\"false\"}) by (pod) * 2) + (sum(kube_pod_status_ready{namespace=~\"$namespace\", pod=~\"$podName\",job=\"kube-state-metrics\", condition=\"true\"}) by (pod) * 3)",
     "legendFormat": "{{condition}}"
    }
   ]
  },
  {
   "title": "Access MO delay seconds",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "unit_agent_cluster_sql_seconds_sum{action!=\"select_version\"}/unit_agent_cluster_sql_seconds_count{action!=\"select_version\"}",
     "legendFormat": "{{cluster_name,action}}"
    }
   ]
  },
  { "title": "UnitControllers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "ReconcilerErrorsQps",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum by(controller) (rate(controller_runtime_reconcile_errors_total{app=\"unit-agent\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ReconcileSeconds",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 19 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, controller_runtime_reconcile_time_seconds_bucket{app=\"unit-agent\"})",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "WorkQueueDurationSeconds",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 19 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, workqueue_queue_duration_seconds_bucket{app=\"unit-agent\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "workQueueRetriesQps",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum by(name) (rate(workqueue_retries_total{app=\"unit-agent\", name!=\"cluster-healthz-checker\"}[1m]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "workQueueDepth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 26 },
   "targets": [
    {
     "expr": "sum by(name) (workqueue_depth{app=\"unit-agent\", name!=\"cluster-healthz-checker\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "ClusterController", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "ObserveClusterSeconds",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(unit_agent_observe_cluster_seconds_bucket[5m])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(unit_agent_observe_cluster_seconds_bucket[5m])))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "UpClusterSeconds",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 34 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(unit_agent_up_cluster_seconds_bucket[5m])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(unit_agent_up_cluster_seconds_bucket[5m])))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "ReconcilePublicEndpointSeconds",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 14, "y": 34 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(unit_agent_reconcile_public_endpoint_seconds_bucket[5m])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(unit_agent_reconcile_public_endpoint_seconds_bucket[5m])))",
     "legendFormat": "p50"
    }
   ]
  },
  { "title": "Certificate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Expirations",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "unit_agent_agent_certificate_expiration_days",
     "legendFormat": "{{certificate_name}}"
    }
   ]
  }
 ]
}