{
 "title": "MOCloud / Instance Service",
 "tags": [ "MO-Cloud" ],
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Instance-Cluster Detail info",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "controlplane_instance_detail_info + on(id) group_left(monthly_quota_status) 0*(sum without (quota_status) (label_replace(controlplane_instance_monthly_cu, \"monthly_quota_status\", \"$1\", \"quota_status\", \"(.*)\")))  +on(id) group_left(quota_status) 0*controlplane_instance_daily_cu  ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Instance Daily CU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    { "expr": "controlplane_instance_daily_cu", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Instance Monthly CU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "controlplane_instance_monthly_cu",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Instance Creation Duration Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "controlplane_instance_creation_duration_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Instance Termination Duration Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "controlplane_instance_termination_duration_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Instance Update Duration Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "controlplane_instance_update_duration_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Instance Recovery Duration Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "controlplane_instance_recovery_duration_seconds",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}