{
 "title": "MOOB / Agent",
 "tags": [
  "MO-Cloud",
  "MO-OB"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "pod",
    "query": {
     "query": "label_values(agent_batch_insert_latency_ms_count{service=\"$service\"}, pod)"
    }
   },
   { "name": "service", "query": "mo-agent-service" },
   { "name": "query0" }
  ]
 },
 "panels": [
  {
   "title": "Collect Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "delta(agent_collect_bytes{service=\"$service\"}[$__interval])",
     "legendFormat": "{{instance}} - {{type}}"
    }
   ]
  },
  {
   "title": "Processed Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "delta(agent_processed_bytes{service=\"$service\"}[$__interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Http Api (QPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "delta(api_response_latency_ms_count{service=\"$service\"}[1m]) / 60",
     "legendFormat": "{{instance}}{{path}}"
    }
   ]
  },
  {
   "title": "Batch Insert (QPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "delta(agent_batch_insert_latency_ms_count{service=\"$service\"}[1m]) / 60",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "agent_connections{service=\"$service\"}",
     "legendFormat": "{{pod}} - {{instance}} - {{type}}"
    }
   ]
  },
  {
   "title": "Batch Insert Sql Length (avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expression": "$A / $B ", "type": "math" }
   ]
  },
  { "title": "latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "response latency (p50)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le, path, instance) (rate(api_response_latency_ms_bucket[$__interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "response latency (p95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, path, instance) (rate(api_response_latency_ms_bucket[$__interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Batch Insert latency (p50)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le, instance) (rate(agent_batch_insert_latency_ms_bucket[$__interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Batch Insert latency (p95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, instance) (rate(agent_batch_insert_latency_ms_bucket[$__interval])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}