{
 "title": "Prometheus / Status",
 "tags": [
  "prometheus-mixin",
  "MO-OB"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "query": {
     "query": "label_values(prometheus_build_info,job)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(prometheus_build_info{job=\"$job\"},instance)"
    }
   },
   { "name": "namespace", "query": "mo-ob" },
   { "name": "cluster" }
  ]
 },
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Head Series",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_tsdb_head_series{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{job}} {{instance}} head series"
    }
   ]
  },
  {
   "title": "series 增长率 ( value > 5)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "deriv(prometheus_tsdb_head_series{job=~\".+\",instance=~\".+\"}[5m]) > 5",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "example count (rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "irate(prometheus_tsdb_head_samples_appended_total{job=~\".*prometheus\",type=\"float\"}[$__rate_interval])",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "instance count (count by namespace, app)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "count by(namespace, app) (up)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory Usage (avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (pod) (container_memory_working_set_bytes{container=\"prometheus\",image!=\"\",pod=~\".*prometheus.*\"}) / avg by (pod) (kube_pod_container_resource_limits{container=\"prometheus\",pod=~\".*prometheus.*\",resource=\"memory\"}) * 100 ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{container=\"prometheus\",image!=\"\",pod=~\".*prometheus.*\"}",
     "legendFormat": "{{instance}} - {{container}}"
    }
   ]
  },
  {
   "title": "Volume Space Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(\n  sum without(instance, node) (topk(1, (kubelet_volume_stats_capacity_bytes{cluster=\"$cluster\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=~\".+prometheus.+\"})))\n  -\n  sum without(instance, node) (topk(1, (kubelet_volume_stats_available_bytes{cluster=\"$cluster\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=~\".+prometheus.+\"})))\n)\n",
     "legendFormat": "Used Space"
    },
    {
     "expr": "sum without(instance, node) (topk(1, (kubelet_volume_stats_available_bytes{cluster=\"$cluster\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=~\".+prometheus.+\"})))\n",
     "legendFormat": "Free Space"
    }
   ]
  },
  {
   "title": "Volume Space Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max without(instance,node) (\n(\n  topk(1, kubelet_volume_stats_capacity_bytes{cluster=\"$cluster\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=~\".+prometheus.+\"})\n  -\n  topk(1, kubelet_volume_stats_available_bytes{cluster=\"$cluster\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=~\".+prometheus.+\"})\n)\n/\ntopk(1, kubelet_volume_stats_capacity_bytes{cluster=\"$cluster\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\", persistentvolumeclaim=~\".+prometheus.+\"})\n* 100)\n"
    }
   ]
  },
  {
   "title": "Flush Op (Avg size)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_compaction_chunk_size_bytes_sum{job=~\".*prometheus\"}[$__rate_interval]) / rate(prometheus_tsdb_compaction_chunk_samples_sum{job=~\".*prometheus\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "example count (histogram)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "irate(prometheus_tsdb_head_samples_appended_total{job=~\".*prometheus\",type=\"histogram\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Analysis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "series count",
     "type": "piechart",
     "gridPos": { "h": 12, "w": 7, "x": 0, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count by(namespace, app) ({namespace=\"mo.\"})",
       "legendFormat": "{{label_name}}"
      },
      {
       "expr": "count by(namespace, app) ({namespace=\"cos-system\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "count by(namespace, app) ({namespace=\"kube-system\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "count by(namespace, app) ({namespace=~\"freetier.*\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "count by(namespace, app) ({namespace=~\"upgrade.*\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "count by(namespace, app) ({app=~\"local-system-service|metric-work\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "avg series count (each instance)",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 17, "x": 7, "y": 17 },
     "targets": [
      {
       "expr": "count by(namespace, app) ({namespace=~\"mo.*\"}) / count by (namespace, app) (up{namespace=~\"mo.*\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "count by(namespace, app) ({namespace=\"cos-system\"}) / count by (namespace, app) (up{namespace=\"cos-system\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "count by(namespace, app) ({namespace=\"kube-system\"}) / count by(namespace, app) (up{namespace=\"kube-system\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "count by(namespace, app) ({namespace=~\"freetier.*\"}) / count by(namespace, app) (up{namespace=~\"freetier.*\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "count by(namespace, app) ({namespace=~\"upgrade.*\"}) / count by(namespace, app) (up{namespace=~\"upgrade.*\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "count by(namespace, app) ({app=~\"local-system-service|metric-work\"}) / count by(namespace, app) (up{app=~\"local-system-service|metric-work\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "instance count (count by namespace, app)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
     "targets": [
      { "expr": "count by(namespace, app) (up)", "legendFormat": "__auto" }
     ]
    }
   ]
  }
 ]
}